// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ezetap.proto

package com.eze.ezecli;

public interface ApiInputOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ezecli.ApiInput)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required .ezecli.ApiInput.MessageType msgType = 1;</code>
   *
   * <pre>
   *&#47; type of API
   * </pre>
   */
  boolean hasMsgType();
  /**
   * <code>required .ezecli.ApiInput.MessageType msgType = 1;</code>
   *
   * <pre>
   *&#47; type of API
   * </pre>
   */
  com.eze.ezecli.ApiInput.MessageType getMsgType();

  /**
   * <code>optional bytes msgData = 2;</code>
   *
   * <pre>
   *&#47; packed data of input message of the API; For Logout, PrepareDevice and Exit APIs there are no corresponding input messages and hence this field should be initialized to NULL
   * </pre>
   */
  boolean hasMsgData();
  /**
   * <code>optional bytes msgData = 2;</code>
   *
   * <pre>
   *&#47; packed data of input message of the API; For Logout, PrepareDevice and Exit APIs there are no corresponding input messages and hence this field should be initialized to NULL
   * </pre>
   */
  com.google.protobuf.ByteString getMsgData();
}
