// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ezetap.proto

package com.eze.ezecli;

public interface ApiOutputOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ezecli.ApiOutput)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required .ezecli.ApiOutput.EventType eventType = 1;</code>
   *
   * <pre>
   *&#47; Event type
   * </pre>
   */
  boolean hasEventType();
  /**
   * <code>required .ezecli.ApiOutput.EventType eventType = 1;</code>
   *
   * <pre>
   *&#47; Event type
   * </pre>
   */
  com.eze.ezecli.ApiOutput.EventType getEventType();

  /**
   * <code>required .ezecli.ApiOutput.ResultStatus status = 2;</code>
   *
   * <pre>
   *&#47; Status of the result; 0 - Success; 1 - Failure
   * </pre>
   */
  boolean hasStatus();
  /**
   * <code>required .ezecli.ApiOutput.ResultStatus status = 2;</code>
   *
   * <pre>
   *&#47; Status of the result; 0 - Success; 1 - Failure
   * </pre>
   */
  com.eze.ezecli.ApiOutput.ResultStatus getStatus();

  /**
   * <code>optional string msgText = 3;</code>
   *
   * <pre>
   *&#47; Text message associated with the event
   * </pre>
   */
  boolean hasMsgText();
  /**
   * <code>optional string msgText = 3;</code>
   *
   * <pre>
   *&#47; Text message associated with the event
   * </pre>
   */
  java.lang.String getMsgText();
  /**
   * <code>optional string msgText = 3;</code>
   *
   * <pre>
   *&#47; Text message associated with the event
   * </pre>
   */
  com.google.protobuf.ByteString
      getMsgTextBytes();

  /**
   * <code>optional bytes outData = 4;</code>
   *
   * <pre>
   *&#47; packed output data of the API; On Failure, it is the packed data of StatusInfo. On Success, it would correspond to the respective Output Message or will be NULL. In progress, it is the packed data of ProgressInfo
   * </pre>
   */
  boolean hasOutData();
  /**
   * <code>optional bytes outData = 4;</code>
   *
   * <pre>
   *&#47; packed output data of the API; On Failure, it is the packed data of StatusInfo. On Success, it would correspond to the respective Output Message or will be NULL. In progress, it is the packed data of ProgressInfo
   * </pre>
   */
  com.google.protobuf.ByteString getOutData();

  /**
   * <code>optional .ezecli.ApiOutput.NotificationType notification = 5;</code>
   *
   * <pre>
   *&#47; Notification Type; applicable only when eventType is API_NOTIFICATION
   * </pre>
   */
  boolean hasNotification();
  /**
   * <code>optional .ezecli.ApiOutput.NotificationType notification = 5;</code>
   *
   * <pre>
   *&#47; Notification Type; applicable only when eventType is API_NOTIFICATION
   * </pre>
   */
  com.eze.ezecli.ApiOutput.NotificationType getNotification();
}
