// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ezetap.proto

package com.eze.ezecli;

public final class Ezetap {
  private Ezetap() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ezecli_ApiInput_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ezecli_ApiInput_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ezecli_ApiOutput_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ezecli_ApiOutput_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ezecli_ChangePasswordInput_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ezecli_ChangePasswordInput_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ezecli_ForwardReceiptInput_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ezecli_ForwardReceiptInput_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ezecli_LoginInput_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ezecli_LoginInput_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ezecli_LoginOutput_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ezecli_LoginOutput_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ezecli_ProgressInfo_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ezecli_ProgressInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ezecli_SignatureInput_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ezecli_SignatureInput_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ezecli_StatusInfo_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ezecli_StatusInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ezecli_TxnDetailsInput_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ezecli_TxnDetailsInput_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ezecli_TxnHistoryInput_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ezecli_TxnHistoryInput_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ezecli_TxnHistory_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ezecli_TxnHistory_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ezecli_TxnHistory_SummaryItem_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ezecli_TxnHistory_SummaryItem_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ezecli_TxnInput_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ezecli_TxnInput_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ezecli_Txn_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ezecli_Txn_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ezecli_TxnStatusInput_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ezecli_TxnStatusInput_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ezecli_VoidTxnInput_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ezecli_VoidTxnInput_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014ezetap.proto\022\006ezecli\"\275\002\n\010ApiInput\022-\n\007m" +
      "sgType\030\001 \002(\0162\034.ezecli.ApiInput.MessageTy" +
      "pe\022\017\n\007msgData\030\002 \001(\014\"\360\001\n\013MessageType\022\010\n\004E" +
      "XIT\020\000\022\t\n\005LOGIN\020\001\022\007\n\003TXN\020\002\022\022\n\016PREPARE_DEV" +
      "ICE\020\003\022\024\n\020ATTACH_SIGNATURE\020\004\022\017\n\013TXN_HISTO" +
      "RY\020\005\022\014\n\010VOID_TXN\020\006\022\023\n\017FORWARD_RECEIPT\020\007\022" +
      "\016\n\nTXN_STATUS\020\010\022\023\n\017CHANGE_PASSWORD\020\t\022\n\n\006" +
      "LOGOUT\020\n\022\017\n\013TXN_DETAILS\020\013\022\020\n\014ENABLE_DEBU" +
      "G\020b\022\021\n\rDISABLE_DEBUG\020c\"\366\010\n\tApiOutput\022.\n\t" +
      "eventType\030\001 \002(\0162\033.ezecli.ApiOutput.Event",
      "Type\022.\n\006status\030\002 \002(\0162\036.ezecli.ApiOutput." +
      "ResultStatus\022\017\n\007msgText\030\003 \001(\t\022\017\n\007outData" +
      "\030\004 \001(\014\0228\n\014notification\030\005 \001(\0162\".ezecli.Ap" +
      "iOutput.NotificationType\"(\n\014ResultStatus" +
      "\022\013\n\007SUCCESS\020\000\022\013\n\007FAILURE\020\001\"\305\002\n\tEventType" +
      "\022\020\n\014LOGIN_RESULT\020\000\022\021\n\rLOGOUT_RESULT\020\001\022\016\n" +
      "\nTXN_RESULT\020\002\022\031\n\025PREPARE_DEVICE_RESULT\020\003" +
      "\022\033\n\027ATTACH_SIGNATURE_RESULT\020\004\022\026\n\022TXN_HIS" +
      "TORY_RESULT\020\005\022\023\n\017VOID_TXN_RESULT\020\006\022\032\n\026FO" +
      "RWARD_RECEIPT_RESULT\020\007\022\025\n\021TXN_STATUS_RES",
      "ULT\020\010\022\032\n\026CHANGE_PASSWORD_RESULT\020\t\022\026\n\022TXN" +
      "_DETAILS_RESULT\020\n\022\020\n\014API_PROGRESS\020\013\022\024\n\020A" +
      "PI_NOTIFICATION\020\014\022\017\n\013EXIT_RESULT\020c\"\272\004\n\020N" +
      "otificationType\022\033\n\027EPIC_IDENTIFYING_DEVI" +
      "CE\020\001\022\032\n\026EPIC_VALIDATING_DEVICE\020\002\022\031\n\025EPIC" +
      "_PREPARING_DEVICE\020\003\022\032\n\026EPIC_PREPARING_FO" +
      "R_TXN\020\004\022\035\n\031EPIC_SWIPE_OR_INSERT_CARD\020\005\022\025" +
      "\n\021EPIC_READING_DATA\020\006\022\030\n\024EPIC_TXN_IN_PRO" +
      "GRESS\020\007\022\022\n\016EPIC_ENTER_PIN\020\010\022\024\n\020EPIC_PIN_" +
      "ENTERED\020\t\022 \n\034EPIC_SERVER_AUTH_IN_PROGRES",
      "S\020\n\022 \n\034EPIC_DEVICE_AUTH_IN_PROGRESS\020\013\022\027\n" +
      "\023EPIC_TXN_TERMINATED\020\014\022\031\n\025EPIC_TXN_NOT_A" +
      "CCEPTED\020\r\022\031\n\025EPIC_UNSUPPORTED_CARD\020\016\022\033\n\027" +
      "EPIC_CARD_NOT_SUPPORTED\020\017\022\025\n\021EPIC_CARD_B" +
      "LOCKED\020\020\022\026\n\022EPIC_CHIP_NOT_READ\020\021\022\026\n\022EPIC" +
      "_USE_CHIP_CARD\020\022\022\022\n\016EPIC_WRONG_PIN\020\023\022\033\n\027" +
      "EPIC_PIN_METHOD_BLOCKED\020\024\022\024\n\020EPIC_EXPIRE" +
      "D_APP\020\025\"C\n\023ChangePasswordInput\022\027\n\017curren" +
      "tPassword\030\001 \002(\t\022\023\n\013newPassword\030\002 \002(\t\"S\n\023" +
      "ForwardReceiptInput\022\r\n\005txnId\030\001 \002(\t\022\026\n\016cu",
      "stomerMobile\030\002 \001(\t\022\025\n\rcustomerEmail\030\003 \001(" +
      "\t\"\207\001\n\nLoginInput\022/\n\tloginMode\030\001 \002(\0162\034.ez" +
      "ecli.LoginInput.LoginMode\022\020\n\010username\030\002 " +
      "\002(\t\022\017\n\007passkey\030\003 \002(\t\"%\n\tLoginMode\022\014\n\010PAS" +
      "SWORD\020\000\022\n\n\006APPKEY\020\001\"3\n\013LoginOutput\022\022\n\nse" +
      "ssionKey\030\001 \001(\t\022\020\n\010settings\030\002 \001(\t\":\n\014Prog" +
      "ressInfo\022\026\n\016stepsCompleted\030\001 \002(\005\022\022\n\ntota" +
      "lSteps\030\002 \002(\005\"\314\001\n\016SignatureInput\022\r\n\005txnId" +
      "\030\001 \002(\t\0223\n\timageType\030\002 \002(\0162 .ezecli.Signa" +
      "tureInput.ImageType\022\022\n\nimageBytes\030\003 \002(\014\022",
      "\016\n\006height\030\004 \001(\005\022\r\n\005width\030\005 \001(\005\022\021\n\ttipAmo" +
      "unt\030\006 \001(\001\"0\n\tImageType\022\007\n\003PNG\020\000\022\007\n\003GIF\020\001" +
      "\022\010\n\004JPEG\020\002\022\007\n\003BMP\020\003\"+\n\nStatusInfo\022\014\n\004cod" +
      "e\030\001 \002(\t\022\017\n\007message\030\002 \002(\t\" \n\017TxnDetailsIn" +
      "put\022\r\n\005txnId\030\001 \002(\t\"4\n\017TxnHistoryInput\022\020\n" +
      "\010strtDate\030\001 \002(\t\022\017\n\007endDate\030\002 \002(\t\"\333\001\n\nTxn" +
      "History\022\022\n\ntotalCount\030\001 \002(\005\022\021\n\tnetAmount" +
      "\030\002 \002(\001\022\030\n\020summaryItemCount\030\003 \002(\005\0224\n\014summ" +
      "aryItems\030\004 \003(\0132\036.ezecli.TxnHistory.Summa" +
      "ryItem\022\031\n\004txns\030\005 \003(\0132\013.ezecli.Txn\032;\n\013Sum",
      "maryItem\022\r\n\005title\030\001 \002(\t\022\r\n\005count\030\002 \002(\005\022\016" +
      "\n\006amount\030\003 \002(\001\"\246\003\n\010TxnInput\022)\n\007txnType\030\001" +
      " \002(\0162\030.ezecli.TxnInput.TxnType\022\016\n\006amount" +
      "\030\002 \002(\001\022\017\n\007orderId\030\003 \001(\t\022\r\n\005nonce\030\004 \001(\t\022\026" +
      "\n\016customerMobile\030\005 \001(\t\022\025\n\rcustomerEmail\030" +
      "\006 \001(\t\022\032\n\022externalReference2\030\007 \001(\t\022\032\n\022ext" +
      "ernalReference3\030\010 \001(\t\022\023\n\013amountOther\030\t \001" +
      "(\001\022\024\n\014chequeNumber\030\n \001(\t\022\020\n\010bankCode\030\013 \001" +
      "(\t\022\022\n\nchequeDate\030\014 \001(\t\022\026\n\016additionalData" +
      "\030\r \001(\t\022\024\n\014receipt_type\030\016 \001(\t\"Y\n\007TxnType\022",
      "\r\n\tCARD_AUTH\020\000\022\021\n\rCARD_PRE_AUTH\020\001\022\026\n\022CAR" +
      "D_PRE_AUTH_CONF\020\002\022\010\n\004CASH\020\003\022\n\n\006CHEQUE\020\004\"" +
      "\242\005\n\003Txn\022$\n\007txnType\030\001 \002(\0162\023.ezecli.Txn.Tx" +
      "nType\022\016\n\006amount\030\002 \002(\001\022\025\n\rtransactionId\030\003" +
      " \002(\t\022\021\n\ttimestamp\030\004 \002(\t\022\022\n\nreceiptUrl\030\005 " +
      "\002(\t\022\017\n\007orderId\030\006 \002(\t\022 \n\030externalReferenc" +
      "eNumber2\030\007 \002(\t\022 \n\030externalReferenceNumbe" +
      "r3\030\010 \002(\t\022\034\n\024customerMobileNumber\030\t \002(\t\022\024" +
      "\n\014customerName\030\n \002(\t\022\016\n\006status\030\013 \002(\t\022\025\n\r" +
      "userAgreement\030\014 \001(\t\022\020\n\010authCode\030\r \001(\t\022\027\n",
      "\017lastFoundDigits\030\016 \001(\t\022\021\n\tcardBrand\030\017 \001(" +
      "\t\022\025\n\rinvoiceNumber\030\020 \001(\t\022\023\n\013batchNumber\030" +
      "\021 \001(\t\022\013\n\003mid\030\022 \001(\t\022\013\n\003tid\030\023 \001(\t\022\030\n\020rever" +
      "seRefNumber\030\024 \001(\t\022\024\n\014chequeNumber\030\025 \001(\t\022" +
      "\020\n\010bankCode\030\026 \001(\t\022\022\n\nchequeDate\030\027 \001(\t\022\030\n" +
      "\020settlementStatus\030\030 \001(\t\022\020\n\010voidable\030\031 \001(" +
      "\010\022\026\n\016serverResponse\030\032 \001(\t\"Y\n\007TxnType\022\r\n\t" +
      "CARD_AUTH\020\000\022\021\n\rCARD_PRE_AUTH\020\001\022\026\n\022CARD_P" +
      "RE_AUTH_CONF\020\002\022\010\n\004CASH\020\003\022\n\n\006CHEQUE\020\004\"\037\n\016" +
      "TxnStatusInput\022\r\n\005nonce\030\001 \002(\t\"\035\n\014VoidTxn",
      "Input\022\r\n\005txnId\030\001 \002(\tB\022\n\016com.eze.ezecliP\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ezecli_ApiInput_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ezecli_ApiInput_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ezecli_ApiInput_descriptor,
        new java.lang.String[] { "MsgType", "MsgData", });
    internal_static_ezecli_ApiOutput_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ezecli_ApiOutput_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ezecli_ApiOutput_descriptor,
        new java.lang.String[] { "EventType", "Status", "MsgText", "OutData", "Notification", });
    internal_static_ezecli_ChangePasswordInput_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ezecli_ChangePasswordInput_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ezecli_ChangePasswordInput_descriptor,
        new java.lang.String[] { "CurrentPassword", "NewPassword", });
    internal_static_ezecli_ForwardReceiptInput_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_ezecli_ForwardReceiptInput_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ezecli_ForwardReceiptInput_descriptor,
        new java.lang.String[] { "TxnId", "CustomerMobile", "CustomerEmail", });
    internal_static_ezecli_LoginInput_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_ezecli_LoginInput_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ezecli_LoginInput_descriptor,
        new java.lang.String[] { "LoginMode", "Username", "Passkey", });
    internal_static_ezecli_LoginOutput_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_ezecli_LoginOutput_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ezecli_LoginOutput_descriptor,
        new java.lang.String[] { "SessionKey", "Settings", });
    internal_static_ezecli_ProgressInfo_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_ezecli_ProgressInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ezecli_ProgressInfo_descriptor,
        new java.lang.String[] { "StepsCompleted", "TotalSteps", });
    internal_static_ezecli_SignatureInput_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_ezecli_SignatureInput_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ezecli_SignatureInput_descriptor,
        new java.lang.String[] { "TxnId", "ImageType", "ImageBytes", "Height", "Width", "TipAmount", });
    internal_static_ezecli_StatusInfo_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_ezecli_StatusInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ezecli_StatusInfo_descriptor,
        new java.lang.String[] { "Code", "Message", });
    internal_static_ezecli_TxnDetailsInput_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_ezecli_TxnDetailsInput_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ezecli_TxnDetailsInput_descriptor,
        new java.lang.String[] { "TxnId", });
    internal_static_ezecli_TxnHistoryInput_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_ezecli_TxnHistoryInput_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ezecli_TxnHistoryInput_descriptor,
        new java.lang.String[] { "StrtDate", "EndDate", });
    internal_static_ezecli_TxnHistory_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_ezecli_TxnHistory_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ezecli_TxnHistory_descriptor,
        new java.lang.String[] { "TotalCount", "NetAmount", "SummaryItemCount", "SummaryItems", "Txns", });
    internal_static_ezecli_TxnHistory_SummaryItem_descriptor =
      internal_static_ezecli_TxnHistory_descriptor.getNestedTypes().get(0);
    internal_static_ezecli_TxnHistory_SummaryItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ezecli_TxnHistory_SummaryItem_descriptor,
        new java.lang.String[] { "Title", "Count", "Amount", });
    internal_static_ezecli_TxnInput_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_ezecli_TxnInput_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ezecli_TxnInput_descriptor,
        new java.lang.String[] { "TxnType", "Amount", "OrderId", "Nonce", "CustomerMobile", "CustomerEmail", "ExternalReference2", "ExternalReference3", "AmountOther", "ChequeNumber", "BankCode", "ChequeDate", "AdditionalData", "ReceiptType", });
    internal_static_ezecli_Txn_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_ezecli_Txn_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ezecli_Txn_descriptor,
        new java.lang.String[] { "TxnType", "Amount", "TransactionId", "Timestamp", "ReceiptUrl", "OrderId", "ExternalReferenceNumber2", "ExternalReferenceNumber3", "CustomerMobileNumber", "CustomerName", "Status", "UserAgreement", "AuthCode", "LastFoundDigits", "CardBrand", "InvoiceNumber", "BatchNumber", "Mid", "Tid", "ReverseRefNumber", "ChequeNumber", "BankCode", "ChequeDate", "SettlementStatus", "Voidable", "ServerResponse", });
    internal_static_ezecli_TxnStatusInput_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_ezecli_TxnStatusInput_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ezecli_TxnStatusInput_descriptor,
        new java.lang.String[] { "Nonce", });
    internal_static_ezecli_VoidTxnInput_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_ezecli_VoidTxnInput_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ezecli_VoidTxnInput_descriptor,
        new java.lang.String[] { "TxnId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
