// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ezetap.proto

package com.eze.ezecli;

/**
 * Protobuf type {@code ezecli.ForwardReceiptInput}
 *
 * <pre>
 **
 * ForwardReceiptInput is a message representing the input for the forward receipt API. API is used to forward e-receipt to the customer. 
 * Please note that all transactions initiated with customer mobile/email in the input for the transaction API, would be notified by default, based on the merchant settings.
 * </pre>
 */
public final class ForwardReceiptInput extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:ezecli.ForwardReceiptInput)
    ForwardReceiptInputOrBuilder {
  // Use ForwardReceiptInput.newBuilder() to construct.
  private ForwardReceiptInput(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private ForwardReceiptInput(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final ForwardReceiptInput defaultInstance;
  public static ForwardReceiptInput getDefaultInstance() {
    return defaultInstance;
  }

  public ForwardReceiptInput getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  @SuppressWarnings("unused")
private ForwardReceiptInput(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000001;
            txnId_ = bs;
            break;
          }
          case 18: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000002;
            customerMobile_ = bs;
            break;
          }
          case 26: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000004;
            customerEmail_ = bs;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.eze.ezecli.Ezetap.internal_static_ezecli_ForwardReceiptInput_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.eze.ezecli.Ezetap.internal_static_ezecli_ForwardReceiptInput_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.eze.ezecli.ForwardReceiptInput.class, com.eze.ezecli.ForwardReceiptInput.Builder.class);
  }

  public static com.google.protobuf.Parser<ForwardReceiptInput> PARSER =
      new com.google.protobuf.AbstractParser<ForwardReceiptInput>() {
    public ForwardReceiptInput parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ForwardReceiptInput(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<ForwardReceiptInput> getParserForType() {
    return PARSER;
  }

  private int bitField0_;
  public static final int TXNID_FIELD_NUMBER = 1;
  private java.lang.Object txnId_;
  /**
   * <code>required string txnId = 1;</code>
   *
   * <pre>
   *&#47; Id of the transaction to be notified to the user
   * </pre>
   */
  public boolean hasTxnId() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>required string txnId = 1;</code>
   *
   * <pre>
   *&#47; Id of the transaction to be notified to the user
   * </pre>
   */
  public java.lang.String getTxnId() {
    java.lang.Object ref = txnId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        txnId_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string txnId = 1;</code>
   *
   * <pre>
   *&#47; Id of the transaction to be notified to the user
   * </pre>
   */
  public com.google.protobuf.ByteString
      getTxnIdBytes() {
    java.lang.Object ref = txnId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      txnId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CUSTOMERMOBILE_FIELD_NUMBER = 2;
  private java.lang.Object customerMobile_;
  /**
   * <code>optional string customerMobile = 2;</code>
   *
   * <pre>
   *&#47; Mobile number of the customer
   * </pre>
   */
  public boolean hasCustomerMobile() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>optional string customerMobile = 2;</code>
   *
   * <pre>
   *&#47; Mobile number of the customer
   * </pre>
   */
  public java.lang.String getCustomerMobile() {
    java.lang.Object ref = customerMobile_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        customerMobile_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string customerMobile = 2;</code>
   *
   * <pre>
   *&#47; Mobile number of the customer
   * </pre>
   */
  public com.google.protobuf.ByteString
      getCustomerMobileBytes() {
    java.lang.Object ref = customerMobile_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      customerMobile_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CUSTOMEREMAIL_FIELD_NUMBER = 3;
  private java.lang.Object customerEmail_;
  /**
   * <code>optional string customerEmail = 3;</code>
   *
   * <pre>
   *&#47; Email address of the customer
   * </pre>
   */
  public boolean hasCustomerEmail() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <code>optional string customerEmail = 3;</code>
   *
   * <pre>
   *&#47; Email address of the customer
   * </pre>
   */
  public java.lang.String getCustomerEmail() {
    java.lang.Object ref = customerEmail_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        customerEmail_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string customerEmail = 3;</code>
   *
   * <pre>
   *&#47; Email address of the customer
   * </pre>
   */
  public com.google.protobuf.ByteString
      getCustomerEmailBytes() {
    java.lang.Object ref = customerEmail_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      customerEmail_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private void initFields() {
    txnId_ = "";
    customerMobile_ = "";
    customerEmail_ = "";
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasTxnId()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeBytes(1, getTxnIdBytes());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeBytes(2, getCustomerMobileBytes());
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeBytes(3, getCustomerEmailBytes());
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, getTxnIdBytes());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, getCustomerMobileBytes());
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(3, getCustomerEmailBytes());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static com.eze.ezecli.ForwardReceiptInput parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.eze.ezecli.ForwardReceiptInput parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.eze.ezecli.ForwardReceiptInput parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.eze.ezecli.ForwardReceiptInput parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.eze.ezecli.ForwardReceiptInput parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.eze.ezecli.ForwardReceiptInput parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static com.eze.ezecli.ForwardReceiptInput parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static com.eze.ezecli.ForwardReceiptInput parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static com.eze.ezecli.ForwardReceiptInput parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.eze.ezecli.ForwardReceiptInput parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(com.eze.ezecli.ForwardReceiptInput prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ezecli.ForwardReceiptInput}
   *
   * <pre>
   **
   * ForwardReceiptInput is a message representing the input for the forward receipt API. API is used to forward e-receipt to the customer. 
   * Please note that all transactions initiated with customer mobile/email in the input for the transaction API, would be notified by default, based on the merchant settings.
   * </pre>
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ezecli.ForwardReceiptInput)
      com.eze.ezecli.ForwardReceiptInputOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.eze.ezecli.Ezetap.internal_static_ezecli_ForwardReceiptInput_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.eze.ezecli.Ezetap.internal_static_ezecli_ForwardReceiptInput_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.eze.ezecli.ForwardReceiptInput.class, com.eze.ezecli.ForwardReceiptInput.Builder.class);
    }

    // Construct using com.eze.ezecli.ForwardReceiptInput.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      txnId_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      customerMobile_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      customerEmail_ = "";
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.eze.ezecli.Ezetap.internal_static_ezecli_ForwardReceiptInput_descriptor;
    }

    public com.eze.ezecli.ForwardReceiptInput getDefaultInstanceForType() {
      return com.eze.ezecli.ForwardReceiptInput.getDefaultInstance();
    }

    public com.eze.ezecli.ForwardReceiptInput build() {
      com.eze.ezecli.ForwardReceiptInput result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.eze.ezecli.ForwardReceiptInput buildPartial() {
      com.eze.ezecli.ForwardReceiptInput result = new com.eze.ezecli.ForwardReceiptInput(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.txnId_ = txnId_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.customerMobile_ = customerMobile_;
      if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
        to_bitField0_ |= 0x00000004;
      }
      result.customerEmail_ = customerEmail_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.eze.ezecli.ForwardReceiptInput) {
        return mergeFrom((com.eze.ezecli.ForwardReceiptInput)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.eze.ezecli.ForwardReceiptInput other) {
      if (other == com.eze.ezecli.ForwardReceiptInput.getDefaultInstance()) return this;
      if (other.hasTxnId()) {
        bitField0_ |= 0x00000001;
        txnId_ = other.txnId_;
        onChanged();
      }
      if (other.hasCustomerMobile()) {
        bitField0_ |= 0x00000002;
        customerMobile_ = other.customerMobile_;
        onChanged();
      }
      if (other.hasCustomerEmail()) {
        bitField0_ |= 0x00000004;
        customerEmail_ = other.customerEmail_;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      if (!hasTxnId()) {
        
        return false;
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.eze.ezecli.ForwardReceiptInput parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.eze.ezecli.ForwardReceiptInput) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object txnId_ = "";
    /**
     * <code>required string txnId = 1;</code>
     *
     * <pre>
     *&#47; Id of the transaction to be notified to the user
     * </pre>
     */
    public boolean hasTxnId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string txnId = 1;</code>
     *
     * <pre>
     *&#47; Id of the transaction to be notified to the user
     * </pre>
     */
    public java.lang.String getTxnId() {
      java.lang.Object ref = txnId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          txnId_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string txnId = 1;</code>
     *
     * <pre>
     *&#47; Id of the transaction to be notified to the user
     * </pre>
     */
    public com.google.protobuf.ByteString
        getTxnIdBytes() {
      java.lang.Object ref = txnId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        txnId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string txnId = 1;</code>
     *
     * <pre>
     *&#47; Id of the transaction to be notified to the user
     * </pre>
     */
    public Builder setTxnId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      txnId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string txnId = 1;</code>
     *
     * <pre>
     *&#47; Id of the transaction to be notified to the user
     * </pre>
     */
    public Builder clearTxnId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      txnId_ = getDefaultInstance().getTxnId();
      onChanged();
      return this;
    }
    /**
     * <code>required string txnId = 1;</code>
     *
     * <pre>
     *&#47; Id of the transaction to be notified to the user
     * </pre>
     */
    public Builder setTxnIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      txnId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object customerMobile_ = "";
    /**
     * <code>optional string customerMobile = 2;</code>
     *
     * <pre>
     *&#47; Mobile number of the customer
     * </pre>
     */
    public boolean hasCustomerMobile() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string customerMobile = 2;</code>
     *
     * <pre>
     *&#47; Mobile number of the customer
     * </pre>
     */
    public java.lang.String getCustomerMobile() {
      java.lang.Object ref = customerMobile_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          customerMobile_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string customerMobile = 2;</code>
     *
     * <pre>
     *&#47; Mobile number of the customer
     * </pre>
     */
    public com.google.protobuf.ByteString
        getCustomerMobileBytes() {
      java.lang.Object ref = customerMobile_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        customerMobile_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string customerMobile = 2;</code>
     *
     * <pre>
     *&#47; Mobile number of the customer
     * </pre>
     */
    public Builder setCustomerMobile(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      customerMobile_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string customerMobile = 2;</code>
     *
     * <pre>
     *&#47; Mobile number of the customer
     * </pre>
     */
    public Builder clearCustomerMobile() {
      bitField0_ = (bitField0_ & ~0x00000002);
      customerMobile_ = getDefaultInstance().getCustomerMobile();
      onChanged();
      return this;
    }
    /**
     * <code>optional string customerMobile = 2;</code>
     *
     * <pre>
     *&#47; Mobile number of the customer
     * </pre>
     */
    public Builder setCustomerMobileBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      customerMobile_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object customerEmail_ = "";
    /**
     * <code>optional string customerEmail = 3;</code>
     *
     * <pre>
     *&#47; Email address of the customer
     * </pre>
     */
    public boolean hasCustomerEmail() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string customerEmail = 3;</code>
     *
     * <pre>
     *&#47; Email address of the customer
     * </pre>
     */
    public java.lang.String getCustomerEmail() {
      java.lang.Object ref = customerEmail_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          customerEmail_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string customerEmail = 3;</code>
     *
     * <pre>
     *&#47; Email address of the customer
     * </pre>
     */
    public com.google.protobuf.ByteString
        getCustomerEmailBytes() {
      java.lang.Object ref = customerEmail_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        customerEmail_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string customerEmail = 3;</code>
     *
     * <pre>
     *&#47; Email address of the customer
     * </pre>
     */
    public Builder setCustomerEmail(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      customerEmail_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string customerEmail = 3;</code>
     *
     * <pre>
     *&#47; Email address of the customer
     * </pre>
     */
    public Builder clearCustomerEmail() {
      bitField0_ = (bitField0_ & ~0x00000004);
      customerEmail_ = getDefaultInstance().getCustomerEmail();
      onChanged();
      return this;
    }
    /**
     * <code>optional string customerEmail = 3;</code>
     *
     * <pre>
     *&#47; Email address of the customer
     * </pre>
     */
    public Builder setCustomerEmailBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      customerEmail_ = value;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:ezecli.ForwardReceiptInput)
  }

  static {
    defaultInstance = new ForwardReceiptInput(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:ezecli.ForwardReceiptInput)
}

