// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ezetap.proto

package com.eze.ezecli;

public interface ForwardReceiptInputOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ezecli.ForwardReceiptInput)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required string txnId = 1;</code>
   *
   * <pre>
   *&#47; Id of the transaction to be notified to the user
   * </pre>
   */
  boolean hasTxnId();
  /**
   * <code>required string txnId = 1;</code>
   *
   * <pre>
   *&#47; Id of the transaction to be notified to the user
   * </pre>
   */
  java.lang.String getTxnId();
  /**
   * <code>required string txnId = 1;</code>
   *
   * <pre>
   *&#47; Id of the transaction to be notified to the user
   * </pre>
   */
  com.google.protobuf.ByteString
      getTxnIdBytes();

  /**
   * <code>optional string customerMobile = 2;</code>
   *
   * <pre>
   *&#47; Mobile number of the customer
   * </pre>
   */
  boolean hasCustomerMobile();
  /**
   * <code>optional string customerMobile = 2;</code>
   *
   * <pre>
   *&#47; Mobile number of the customer
   * </pre>
   */
  java.lang.String getCustomerMobile();
  /**
   * <code>optional string customerMobile = 2;</code>
   *
   * <pre>
   *&#47; Mobile number of the customer
   * </pre>
   */
  com.google.protobuf.ByteString
      getCustomerMobileBytes();

  /**
   * <code>optional string customerEmail = 3;</code>
   *
   * <pre>
   *&#47; Email address of the customer
   * </pre>
   */
  boolean hasCustomerEmail();
  /**
   * <code>optional string customerEmail = 3;</code>
   *
   * <pre>
   *&#47; Email address of the customer
   * </pre>
   */
  java.lang.String getCustomerEmail();
  /**
   * <code>optional string customerEmail = 3;</code>
   *
   * <pre>
   *&#47; Email address of the customer
   * </pre>
   */
  com.google.protobuf.ByteString
      getCustomerEmailBytes();
}
