// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ezetap.proto

package com.eze.ezecli;

public interface LoginInputOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ezecli.LoginInput)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required .ezecli.LoginInput.LoginMode loginMode = 1;</code>
   *
   * <pre>
   *&#47; Mode of login
   * </pre>
   */
  boolean hasLoginMode();
  /**
   * <code>required .ezecli.LoginInput.LoginMode loginMode = 1;</code>
   *
   * <pre>
   *&#47; Mode of login
   * </pre>
   */
  com.eze.ezecli.LoginInput.LoginMode getLoginMode();

  /**
   * <code>required string username = 2;</code>
   *
   * <pre>
   *&#47; Username of the user to login
   * </pre>
   */
  boolean hasUsername();
  /**
   * <code>required string username = 2;</code>
   *
   * <pre>
   *&#47; Username of the user to login
   * </pre>
   */
  java.lang.String getUsername();
  /**
   * <code>required string username = 2;</code>
   *
   * <pre>
   *&#47; Username of the user to login
   * </pre>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>required string passkey = 3;</code>
   *
   * <pre>
   *&#47; App_key or password to be used while login; App_key is the preferred mode of login. 
   * </pre>
   */
  boolean hasPasskey();
  /**
   * <code>required string passkey = 3;</code>
   *
   * <pre>
   *&#47; App_key or password to be used while login; App_key is the preferred mode of login. 
   * </pre>
   */
  java.lang.String getPasskey();
  /**
   * <code>required string passkey = 3;</code>
   *
   * <pre>
   *&#47; App_key or password to be used while login; App_key is the preferred mode of login. 
   * </pre>
   */
  com.google.protobuf.ByteString
      getPasskeyBytes();
}
