// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ezetap.proto

package com.eze.ezecli;

public interface LoginOutputOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ezecli.LoginOutput)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string sessionKey = 1;</code>
   *
   * <pre>
   *Session Key of the logged in user
   * </pre>
   */
  boolean hasSessionKey();
  /**
   * <code>optional string sessionKey = 1;</code>
   *
   * <pre>
   *Session Key of the logged in user
   * </pre>
   */
  java.lang.String getSessionKey();
  /**
   * <code>optional string sessionKey = 1;</code>
   *
   * <pre>
   *Session Key of the logged in user
   * </pre>
   */
  com.google.protobuf.ByteString
      getSessionKeyBytes();

  /**
   * <code>optional string settings = 2;</code>
   *
   * <pre>
   *User/Merchant settings
   * </pre>
   */
  boolean hasSettings();
  /**
   * <code>optional string settings = 2;</code>
   *
   * <pre>
   *User/Merchant settings
   * </pre>
   */
  java.lang.String getSettings();
  /**
   * <code>optional string settings = 2;</code>
   *
   * <pre>
   *User/Merchant settings
   * </pre>
   */
  com.google.protobuf.ByteString
      getSettingsBytes();
}
