// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ezetap.proto

package com.eze.ezecli;

public interface ProgressInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ezecli.ProgressInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required int32 stepsCompleted = 1;</code>
   *
   * <pre>
   *&#47; Steps completed so far in the API
   * </pre>
   */
  boolean hasStepsCompleted();
  /**
   * <code>required int32 stepsCompleted = 1;</code>
   *
   * <pre>
   *&#47; Steps completed so far in the API
   * </pre>
   */
  int getStepsCompleted();

  /**
   * <code>required int32 totalSteps = 2;</code>
   *
   * <pre>
   *&#47; Total no. of steps in the API
   * </pre>
   */
  boolean hasTotalSteps();
  /**
   * <code>required int32 totalSteps = 2;</code>
   *
   * <pre>
   *&#47; Total no. of steps in the API
   * </pre>
   */
  int getTotalSteps();
}
