// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ezetap.proto

package com.eze.ezecli;

public interface StatusInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ezecli.StatusInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required string code = 1;</code>
   *
   * <pre>
   *&#47; Error code sent from the server
   * </pre>
   */
  boolean hasCode();
  /**
   * <code>required string code = 1;</code>
   *
   * <pre>
   *&#47; Error code sent from the server
   * </pre>
   */
  java.lang.String getCode();
  /**
   * <code>required string code = 1;</code>
   *
   * <pre>
   *&#47; Error code sent from the server
   * </pre>
   */
  com.google.protobuf.ByteString
      getCodeBytes();

  /**
   * <code>required string message = 2;</code>
   *
   * <pre>
   *&#47; Error message sent from the server
   * </pre>
   */
  boolean hasMessage();
  /**
   * <code>required string message = 2;</code>
   *
   * <pre>
   *&#47; Error message sent from the server
   * </pre>
   */
  java.lang.String getMessage();
  /**
   * <code>required string message = 2;</code>
   *
   * <pre>
   *&#47; Error message sent from the server
   * </pre>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
