// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ezetap.proto

package com.eze.ezecli;

public interface TxnDetailsInputOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ezecli.TxnDetailsInput)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required string txnId = 1;</code>
   *
   * <pre>
   *&#47;Id of the transaction
   * </pre>
   */
  boolean hasTxnId();
  /**
   * <code>required string txnId = 1;</code>
   *
   * <pre>
   *&#47;Id of the transaction
   * </pre>
   */
  java.lang.String getTxnId();
  /**
   * <code>required string txnId = 1;</code>
   *
   * <pre>
   *&#47;Id of the transaction
   * </pre>
   */
  com.google.protobuf.ByteString
      getTxnIdBytes();
}
