// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ezetap.proto

package com.eze.ezecli;

public interface TxnHistoryInputOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ezecli.TxnHistoryInput)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required string strtDate = 1;</code>
   *
   * <pre>
   *&#47;Date from when the transactions are retrieved.
   * </pre>
   */
  boolean hasStrtDate();
  /**
   * <code>required string strtDate = 1;</code>
   *
   * <pre>
   *&#47;Date from when the transactions are retrieved.
   * </pre>
   */
  java.lang.String getStrtDate();
  /**
   * <code>required string strtDate = 1;</code>
   *
   * <pre>
   *&#47;Date from when the transactions are retrieved.
   * </pre>
   */
  com.google.protobuf.ByteString
      getStrtDateBytes();

  /**
   * <code>required string endDate = 2;</code>
   *
   * <pre>
   *&#47;Date to when the transactions are retrieved.
   * </pre>
   */
  boolean hasEndDate();
  /**
   * <code>required string endDate = 2;</code>
   *
   * <pre>
   *&#47;Date to when the transactions are retrieved.
   * </pre>
   */
  java.lang.String getEndDate();
  /**
   * <code>required string endDate = 2;</code>
   *
   * <pre>
   *&#47;Date to when the transactions are retrieved.
   * </pre>
   */
  com.google.protobuf.ByteString
      getEndDateBytes();
}
