// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ezetap.proto

package com.eze.ezecli;

/**
 * Protobuf type {@code ezecli.TxnHistoryInput}
 *
 * <pre>
 **
 * TxnHistoryInput is a message representing the input to the transaction history API. This API is used to get this history of transactions for the current user give
 * a start date and end date. API returns a list of transaction records. The number of records to be fetched is a setting on the Ezetap Server.
 * </pre>
 */
public final class TxnHistoryInput extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:ezecli.TxnHistoryInput)
    TxnHistoryInputOrBuilder {
  // Use TxnHistoryInput.newBuilder() to construct.
  private TxnHistoryInput(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private TxnHistoryInput(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final TxnHistoryInput defaultInstance;
  public static TxnHistoryInput getDefaultInstance() {
    return defaultInstance;
  }

  public TxnHistoryInput getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private TxnHistoryInput(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000001;
            strtDate_ = bs;
            break;
          }
          case 18: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000002;
            endDate_ = bs;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.eze.ezecli.Ezetap.internal_static_ezecli_TxnHistoryInput_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.eze.ezecli.Ezetap.internal_static_ezecli_TxnHistoryInput_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.eze.ezecli.TxnHistoryInput.class, com.eze.ezecli.TxnHistoryInput.Builder.class);
  }

  public static com.google.protobuf.Parser<TxnHistoryInput> PARSER =
      new com.google.protobuf.AbstractParser<TxnHistoryInput>() {
    public TxnHistoryInput parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TxnHistoryInput(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<TxnHistoryInput> getParserForType() {
    return PARSER;
  }

  private int bitField0_;
  public static final int STRTDATE_FIELD_NUMBER = 1;
  private java.lang.Object strtDate_;
  /**
   * <code>required string strtDate = 1;</code>
   *
   * <pre>
   *&#47;Date from when the transactions are retrieved.
   * </pre>
   */
  public boolean hasStrtDate() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>required string strtDate = 1;</code>
   *
   * <pre>
   *&#47;Date from when the transactions are retrieved.
   * </pre>
   */
  public java.lang.String getStrtDate() {
    java.lang.Object ref = strtDate_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        strtDate_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string strtDate = 1;</code>
   *
   * <pre>
   *&#47;Date from when the transactions are retrieved.
   * </pre>
   */
  public com.google.protobuf.ByteString
      getStrtDateBytes() {
    java.lang.Object ref = strtDate_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      strtDate_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ENDDATE_FIELD_NUMBER = 2;
  private java.lang.Object endDate_;
  /**
   * <code>required string endDate = 2;</code>
   *
   * <pre>
   *&#47;Date to when the transactions are retrieved.
   * </pre>
   */
  public boolean hasEndDate() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>required string endDate = 2;</code>
   *
   * <pre>
   *&#47;Date to when the transactions are retrieved.
   * </pre>
   */
  public java.lang.String getEndDate() {
    java.lang.Object ref = endDate_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        endDate_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string endDate = 2;</code>
   *
   * <pre>
   *&#47;Date to when the transactions are retrieved.
   * </pre>
   */
  public com.google.protobuf.ByteString
      getEndDateBytes() {
    java.lang.Object ref = endDate_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      endDate_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private void initFields() {
    strtDate_ = "";
    endDate_ = "";
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasStrtDate()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasEndDate()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeBytes(1, getStrtDateBytes());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeBytes(2, getEndDateBytes());
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, getStrtDateBytes());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, getEndDateBytes());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static com.eze.ezecli.TxnHistoryInput parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.eze.ezecli.TxnHistoryInput parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.eze.ezecli.TxnHistoryInput parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.eze.ezecli.TxnHistoryInput parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.eze.ezecli.TxnHistoryInput parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.eze.ezecli.TxnHistoryInput parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static com.eze.ezecli.TxnHistoryInput parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static com.eze.ezecli.TxnHistoryInput parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static com.eze.ezecli.TxnHistoryInput parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.eze.ezecli.TxnHistoryInput parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(com.eze.ezecli.TxnHistoryInput prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ezecli.TxnHistoryInput}
   *
   * <pre>
   **
   * TxnHistoryInput is a message representing the input to the transaction history API. This API is used to get this history of transactions for the current user give
   * a start date and end date. API returns a list of transaction records. The number of records to be fetched is a setting on the Ezetap Server.
   * </pre>
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ezecli.TxnHistoryInput)
      com.eze.ezecli.TxnHistoryInputOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.eze.ezecli.Ezetap.internal_static_ezecli_TxnHistoryInput_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.eze.ezecli.Ezetap.internal_static_ezecli_TxnHistoryInput_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.eze.ezecli.TxnHistoryInput.class, com.eze.ezecli.TxnHistoryInput.Builder.class);
    }

    // Construct using com.eze.ezecli.TxnHistoryInput.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      strtDate_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      endDate_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.eze.ezecli.Ezetap.internal_static_ezecli_TxnHistoryInput_descriptor;
    }

    public com.eze.ezecli.TxnHistoryInput getDefaultInstanceForType() {
      return com.eze.ezecli.TxnHistoryInput.getDefaultInstance();
    }

    public com.eze.ezecli.TxnHistoryInput build() {
      com.eze.ezecli.TxnHistoryInput result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.eze.ezecli.TxnHistoryInput buildPartial() {
      com.eze.ezecli.TxnHistoryInput result = new com.eze.ezecli.TxnHistoryInput(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.strtDate_ = strtDate_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.endDate_ = endDate_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.eze.ezecli.TxnHistoryInput) {
        return mergeFrom((com.eze.ezecli.TxnHistoryInput)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.eze.ezecli.TxnHistoryInput other) {
      if (other == com.eze.ezecli.TxnHistoryInput.getDefaultInstance()) return this;
      if (other.hasStrtDate()) {
        bitField0_ |= 0x00000001;
        strtDate_ = other.strtDate_;
        onChanged();
      }
      if (other.hasEndDate()) {
        bitField0_ |= 0x00000002;
        endDate_ = other.endDate_;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      if (!hasStrtDate()) {
        
        return false;
      }
      if (!hasEndDate()) {
        
        return false;
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.eze.ezecli.TxnHistoryInput parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.eze.ezecli.TxnHistoryInput) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object strtDate_ = "";
    /**
     * <code>required string strtDate = 1;</code>
     *
     * <pre>
     *&#47;Date from when the transactions are retrieved.
     * </pre>
     */
    public boolean hasStrtDate() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string strtDate = 1;</code>
     *
     * <pre>
     *&#47;Date from when the transactions are retrieved.
     * </pre>
     */
    public java.lang.String getStrtDate() {
      java.lang.Object ref = strtDate_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          strtDate_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string strtDate = 1;</code>
     *
     * <pre>
     *&#47;Date from when the transactions are retrieved.
     * </pre>
     */
    public com.google.protobuf.ByteString
        getStrtDateBytes() {
      java.lang.Object ref = strtDate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        strtDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string strtDate = 1;</code>
     *
     * <pre>
     *&#47;Date from when the transactions are retrieved.
     * </pre>
     */
    public Builder setStrtDate(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      strtDate_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string strtDate = 1;</code>
     *
     * <pre>
     *&#47;Date from when the transactions are retrieved.
     * </pre>
     */
    public Builder clearStrtDate() {
      bitField0_ = (bitField0_ & ~0x00000001);
      strtDate_ = getDefaultInstance().getStrtDate();
      onChanged();
      return this;
    }
    /**
     * <code>required string strtDate = 1;</code>
     *
     * <pre>
     *&#47;Date from when the transactions are retrieved.
     * </pre>
     */
    public Builder setStrtDateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      strtDate_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object endDate_ = "";
    /**
     * <code>required string endDate = 2;</code>
     *
     * <pre>
     *&#47;Date to when the transactions are retrieved.
     * </pre>
     */
    public boolean hasEndDate() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string endDate = 2;</code>
     *
     * <pre>
     *&#47;Date to when the transactions are retrieved.
     * </pre>
     */
    public java.lang.String getEndDate() {
      java.lang.Object ref = endDate_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          endDate_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string endDate = 2;</code>
     *
     * <pre>
     *&#47;Date to when the transactions are retrieved.
     * </pre>
     */
    public com.google.protobuf.ByteString
        getEndDateBytes() {
      java.lang.Object ref = endDate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        endDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string endDate = 2;</code>
     *
     * <pre>
     *&#47;Date to when the transactions are retrieved.
     * </pre>
     */
    public Builder setEndDate(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      endDate_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string endDate = 2;</code>
     *
     * <pre>
     *&#47;Date to when the transactions are retrieved.
     * </pre>
     */
    public Builder clearEndDate() {
      bitField0_ = (bitField0_ & ~0x00000002);
      endDate_ = getDefaultInstance().getEndDate();
      onChanged();
      return this;
    }
    /**
     * <code>required string endDate = 2;</code>
     *
     * <pre>
     *&#47;Date to when the transactions are retrieved.
     * </pre>
     */
    public Builder setEndDateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      endDate_ = value;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:ezecli.TxnHistoryInput)
  }

  static {
    defaultInstance = new TxnHistoryInput(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:ezecli.TxnHistoryInput)
}

