// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ezetap.proto

package com.eze.ezecli;

/**
 * Protobuf type {@code ezecli.TxnInput}
 *
 * <pre>
 **
 * TxnInput is a message representing the input to the transaction API. This API is used to initiate a transaction on the Ezetap Payment when you want to accept a payment.
 * </pre>
 */
public final class TxnInput extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:ezecli.TxnInput)
    TxnInputOrBuilder {
  // Use TxnInput.newBuilder() to construct.
  private TxnInput(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private TxnInput(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final TxnInput defaultInstance;
  public static TxnInput getDefaultInstance() {
    return defaultInstance;
  }

  public TxnInput getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  @SuppressWarnings("unused")
private TxnInput(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            int rawValue = input.readEnum();
            com.eze.ezecli.TxnInput.TxnType value = com.eze.ezecli.TxnInput.TxnType.valueOf(rawValue);
            if (value == null) {
              unknownFields.mergeVarintField(1, rawValue);
            } else {
              bitField0_ |= 0x00000001;
              txnType_ = value;
            }
            break;
          }
          case 17: {
            bitField0_ |= 0x00000002;
            amount_ = input.readDouble();
            break;
          }
          case 26: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000004;
            orderId_ = bs;
            break;
          }
          case 34: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000008;
            nonce_ = bs;
            break;
          }
          case 42: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000010;
            customerMobile_ = bs;
            break;
          }
          case 50: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000020;
            customerEmail_ = bs;
            break;
          }
          case 58: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000040;
            externalReference2_ = bs;
            break;
          }
          case 66: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000080;
            externalReference3_ = bs;
            break;
          }
          case 73: {
            bitField0_ |= 0x00000100;
            amountOther_ = input.readDouble();
            break;
          }
          case 82: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000200;
            chequeNumber_ = bs;
            break;
          }
          case 90: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000400;
            bankCode_ = bs;
            break;
          }
          case 98: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000800;
            chequeDate_ = bs;
            break;
          }
          case 106: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00001000;
            additionalData_ = bs;
            break;
          }
          case 114: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00002000;
            receiptType_ = bs;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.eze.ezecli.Ezetap.internal_static_ezecli_TxnInput_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.eze.ezecli.Ezetap.internal_static_ezecli_TxnInput_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.eze.ezecli.TxnInput.class, com.eze.ezecli.TxnInput.Builder.class);
  }

  public static com.google.protobuf.Parser<TxnInput> PARSER =
      new com.google.protobuf.AbstractParser<TxnInput>() {
    public TxnInput parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TxnInput(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<TxnInput> getParserForType() {
    return PARSER;
  }

  /**
   * Protobuf enum {@code ezecli.TxnInput.TxnType}
   *
   * <pre>
   **
   * TxnType is an enum representing all available types of transaction
   * </pre>
   */
  public enum TxnType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>CARD_AUTH = 0;</code>
     *
     * <pre>
     *&#47;Transaction with CARD
     * </pre>
     */
    CARD_AUTH(0, 0),
    /**
     * <code>CARD_PRE_AUTH = 1;</code>
     *
     * <pre>
     *&#47;Transaction with CARD and PRE_AUTH
     * </pre>
     */
    CARD_PRE_AUTH(1, 1),
    /**
     * <code>CARD_PRE_AUTH_CONF = 2;</code>
     *
     * <pre>
     *&#47;Transaction with CARD and PRE_AUTH confirmation
     * </pre>
     */
    CARD_PRE_AUTH_CONF(2, 2),
    /**
     * <code>CASH = 3;</code>
     *
     * <pre>
     *&#47;Cash transaction
     * </pre>
     */
    CASH(3, 3),
    /**
     * <code>CHEQUE = 4;</code>
     *
     * <pre>
     *&#47;Cheque transcation
     * </pre>
     */
    CHEQUE(4, 4),
    ;

    /**
     * <code>CARD_AUTH = 0;</code>
     *
     * <pre>
     *&#47;Transaction with CARD
     * </pre>
     */
    public static final int CARD_AUTH_VALUE = 0;
    /**
     * <code>CARD_PRE_AUTH = 1;</code>
     *
     * <pre>
     *&#47;Transaction with CARD and PRE_AUTH
     * </pre>
     */
    public static final int CARD_PRE_AUTH_VALUE = 1;
    /**
     * <code>CARD_PRE_AUTH_CONF = 2;</code>
     *
     * <pre>
     *&#47;Transaction with CARD and PRE_AUTH confirmation
     * </pre>
     */
    public static final int CARD_PRE_AUTH_CONF_VALUE = 2;
    /**
     * <code>CASH = 3;</code>
     *
     * <pre>
     *&#47;Cash transaction
     * </pre>
     */
    public static final int CASH_VALUE = 3;
    /**
     * <code>CHEQUE = 4;</code>
     *
     * <pre>
     *&#47;Cheque transcation
     * </pre>
     */
    public static final int CHEQUE_VALUE = 4;


    public final int getNumber() { return value; }

    public static TxnType valueOf(int value) {
      switch (value) {
        case 0: return CARD_AUTH;
        case 1: return CARD_PRE_AUTH;
        case 2: return CARD_PRE_AUTH_CONF;
        case 3: return CASH;
        case 4: return CHEQUE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<TxnType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<TxnType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<TxnType>() {
            public TxnType findValueByNumber(int number) {
              return TxnType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.eze.ezecli.TxnInput.getDescriptor().getEnumTypes().get(0);
    }

    private static final TxnType[] VALUES = values();

    public static TxnType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private TxnType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:ezecli.TxnInput.TxnType)
  }

  private int bitField0_;
  public static final int TXNTYPE_FIELD_NUMBER = 1;
  private com.eze.ezecli.TxnInput.TxnType txnType_;
  /**
   * <code>required .ezecli.TxnInput.TxnType txnType = 1;</code>
   *
   * <pre>
   *&#47;Type of the transaction
   * </pre>
   */
  public boolean hasTxnType() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>required .ezecli.TxnInput.TxnType txnType = 1;</code>
   *
   * <pre>
   *&#47;Type of the transaction
   * </pre>
   */
  public com.eze.ezecli.TxnInput.TxnType getTxnType() {
    return txnType_;
  }

  public static final int AMOUNT_FIELD_NUMBER = 2;
  private double amount_;
  /**
   * <code>required double amount = 2;</code>
   *
   * <pre>
   *&#47;Amount for the transaction
   * </pre>
   */
  public boolean hasAmount() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>required double amount = 2;</code>
   *
   * <pre>
   *&#47;Amount for the transaction
   * </pre>
   */
  public double getAmount() {
    return amount_;
  }

  public static final int ORDERID_FIELD_NUMBER = 3;
  private java.lang.Object orderId_;
  /**
   * <code>optional string orderId = 3;</code>
   *
   * <pre>
   *&#47;Order Id corresponding to the transaction
   * </pre>
   */
  public boolean hasOrderId() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <code>optional string orderId = 3;</code>
   *
   * <pre>
   *&#47;Order Id corresponding to the transaction
   * </pre>
   */
  public java.lang.String getOrderId() {
    java.lang.Object ref = orderId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        orderId_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string orderId = 3;</code>
   *
   * <pre>
   *&#47;Order Id corresponding to the transaction
   * </pre>
   */
  public com.google.protobuf.ByteString
      getOrderIdBytes() {
    java.lang.Object ref = orderId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      orderId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NONCE_FIELD_NUMBER = 4;
  private java.lang.Object nonce_;
  /**
   * <code>optional string nonce = 4;</code>
   *
   * <pre>
   *&#47;Unique identifier for the transaction on the client app.
   * </pre>
   */
  public boolean hasNonce() {
    return ((bitField0_ & 0x00000008) == 0x00000008);
  }
  /**
   * <code>optional string nonce = 4;</code>
   *
   * <pre>
   *&#47;Unique identifier for the transaction on the client app.
   * </pre>
   */
  public java.lang.String getNonce() {
    java.lang.Object ref = nonce_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        nonce_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string nonce = 4;</code>
   *
   * <pre>
   *&#47;Unique identifier for the transaction on the client app.
   * </pre>
   */
  public com.google.protobuf.ByteString
      getNonceBytes() {
    java.lang.Object ref = nonce_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      nonce_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CUSTOMERMOBILE_FIELD_NUMBER = 5;
  private java.lang.Object customerMobile_;
  /**
   * <code>optional string customerMobile = 5;</code>
   *
   * <pre>
   *&#47;Mobile number of the transaction
   * </pre>
   */
  public boolean hasCustomerMobile() {
    return ((bitField0_ & 0x00000010) == 0x00000010);
  }
  /**
   * <code>optional string customerMobile = 5;</code>
   *
   * <pre>
   *&#47;Mobile number of the transaction
   * </pre>
   */
  public java.lang.String getCustomerMobile() {
    java.lang.Object ref = customerMobile_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        customerMobile_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string customerMobile = 5;</code>
   *
   * <pre>
   *&#47;Mobile number of the transaction
   * </pre>
   */
  public com.google.protobuf.ByteString
      getCustomerMobileBytes() {
    java.lang.Object ref = customerMobile_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      customerMobile_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CUSTOMEREMAIL_FIELD_NUMBER = 6;
  private java.lang.Object customerEmail_;
  /**
   * <code>optional string customerEmail = 6;</code>
   *
   * <pre>
   *&#47;Email address of the transaction
   * </pre>
   */
  public boolean hasCustomerEmail() {
    return ((bitField0_ & 0x00000020) == 0x00000020);
  }
  /**
   * <code>optional string customerEmail = 6;</code>
   *
   * <pre>
   *&#47;Email address of the transaction
   * </pre>
   */
  public java.lang.String getCustomerEmail() {
    java.lang.Object ref = customerEmail_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        customerEmail_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string customerEmail = 6;</code>
   *
   * <pre>
   *&#47;Email address of the transaction
   * </pre>
   */
  public com.google.protobuf.ByteString
      getCustomerEmailBytes() {
    java.lang.Object ref = customerEmail_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      customerEmail_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EXTERNALREFERENCE2_FIELD_NUMBER = 7;
  private java.lang.Object externalReference2_;
  /**
   * <code>optional string externalReference2 = 7;</code>
   *
   * <pre>
   *&#47;External reference 2
   * </pre>
   */
  public boolean hasExternalReference2() {
    return ((bitField0_ & 0x00000040) == 0x00000040);
  }
  /**
   * <code>optional string externalReference2 = 7;</code>
   *
   * <pre>
   *&#47;External reference 2
   * </pre>
   */
  public java.lang.String getExternalReference2() {
    java.lang.Object ref = externalReference2_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        externalReference2_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string externalReference2 = 7;</code>
   *
   * <pre>
   *&#47;External reference 2
   * </pre>
   */
  public com.google.protobuf.ByteString
      getExternalReference2Bytes() {
    java.lang.Object ref = externalReference2_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      externalReference2_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EXTERNALREFERENCE3_FIELD_NUMBER = 8;
  private java.lang.Object externalReference3_;
  /**
   * <code>optional string externalReference3 = 8;</code>
   *
   * <pre>
   *&#47;External reference 3
   * </pre>
   */
  public boolean hasExternalReference3() {
    return ((bitField0_ & 0x00000080) == 0x00000080);
  }
  /**
   * <code>optional string externalReference3 = 8;</code>
   *
   * <pre>
   *&#47;External reference 3
   * </pre>
   */
  public java.lang.String getExternalReference3() {
    java.lang.Object ref = externalReference3_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        externalReference3_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string externalReference3 = 8;</code>
   *
   * <pre>
   *&#47;External reference 3
   * </pre>
   */
  public com.google.protobuf.ByteString
      getExternalReference3Bytes() {
    java.lang.Object ref = externalReference3_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      externalReference3_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AMOUNTOTHER_FIELD_NUMBER = 9;
  private double amountOther_;
  /**
   * <code>optional double amountOther = 9;</code>
   *
   * <pre>
   *&#47;Other Amount; In case of cash back transactions. 
   * </pre>
   */
  public boolean hasAmountOther() {
    return ((bitField0_ & 0x00000100) == 0x00000100);
  }
  /**
   * <code>optional double amountOther = 9;</code>
   *
   * <pre>
   *&#47;Other Amount; In case of cash back transactions. 
   * </pre>
   */
  public double getAmountOther() {
    return amountOther_;
  }

  public static final int CHEQUENUMBER_FIELD_NUMBER = 10;
  private java.lang.Object chequeNumber_;
  /**
   * <code>optional string chequeNumber = 10;</code>
   *
   * <pre>
   *&#47;Cheque number if the transaction type is CHEQUE
   * </pre>
   */
  public boolean hasChequeNumber() {
    return ((bitField0_ & 0x00000200) == 0x00000200);
  }
  /**
   * <code>optional string chequeNumber = 10;</code>
   *
   * <pre>
   *&#47;Cheque number if the transaction type is CHEQUE
   * </pre>
   */
  public java.lang.String getChequeNumber() {
    java.lang.Object ref = chequeNumber_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        chequeNumber_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string chequeNumber = 10;</code>
   *
   * <pre>
   *&#47;Cheque number if the transaction type is CHEQUE
   * </pre>
   */
  public com.google.protobuf.ByteString
      getChequeNumberBytes() {
    java.lang.Object ref = chequeNumber_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      chequeNumber_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BANKCODE_FIELD_NUMBER = 11;
  private java.lang.Object bankCode_;
  /**
   * <code>optional string bankCode = 11;</code>
   *
   * <pre>
   *&#47;MICR code of the bank for CHEQUE payments
   * </pre>
   */
  public boolean hasBankCode() {
    return ((bitField0_ & 0x00000400) == 0x00000400);
  }
  /**
   * <code>optional string bankCode = 11;</code>
   *
   * <pre>
   *&#47;MICR code of the bank for CHEQUE payments
   * </pre>
   */
  public java.lang.String getBankCode() {
    java.lang.Object ref = bankCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        bankCode_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string bankCode = 11;</code>
   *
   * <pre>
   *&#47;MICR code of the bank for CHEQUE payments
   * </pre>
   */
  public com.google.protobuf.ByteString
      getBankCodeBytes() {
    java.lang.Object ref = bankCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      bankCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CHEQUEDATE_FIELD_NUMBER = 12;
  private java.lang.Object chequeDate_;
  /**
   * <code>optional string chequeDate = 12;</code>
   *
   * <pre>
   *&#47;Date on the cheque for CHEQUE payments
   * </pre>
   */
  public boolean hasChequeDate() {
    return ((bitField0_ & 0x00000800) == 0x00000800);
  }
  /**
   * <code>optional string chequeDate = 12;</code>
   *
   * <pre>
   *&#47;Date on the cheque for CHEQUE payments
   * </pre>
   */
  public java.lang.String getChequeDate() {
    java.lang.Object ref = chequeDate_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        chequeDate_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string chequeDate = 12;</code>
   *
   * <pre>
   *&#47;Date on the cheque for CHEQUE payments
   * </pre>
   */
  public com.google.protobuf.ByteString
      getChequeDateBytes() {
    java.lang.Object ref = chequeDate_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      chequeDate_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ADDITIONALDATA_FIELD_NUMBER = 13;
  private java.lang.Object additionalData_;
  /**
   * <code>optional string additionalData = 13;</code>
   *
   * <pre>
   *&#47;Any additional JSON data to be appended to the transaction input 
   * </pre>
   */
  public boolean hasAdditionalData() {
    return ((bitField0_ & 0x00001000) == 0x00001000);
  }
  /**
   * <code>optional string additionalData = 13;</code>
   *
   * <pre>
   *&#47;Any additional JSON data to be appended to the transaction input 
   * </pre>
   */
  public java.lang.String getAdditionalData() {
    java.lang.Object ref = additionalData_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        additionalData_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string additionalData = 13;</code>
   *
   * <pre>
   *&#47;Any additional JSON data to be appended to the transaction input 
   * </pre>
   */
  public com.google.protobuf.ByteString
      getAdditionalDataBytes() {
    java.lang.Object ref = additionalData_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      additionalData_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RECEIPT_TYPE_FIELD_NUMBER = 14;
  private java.lang.Object receiptType_;
  /**
   * <code>optional string receipt_type = 14;</code>
   *
   * <pre>
   *&#47;Type of receipt. Ex: eSignature, paper, receipt_cart
   * </pre>
   */
  public boolean hasReceiptType() {
    return ((bitField0_ & 0x00002000) == 0x00002000);
  }
  /**
   * <code>optional string receipt_type = 14;</code>
   *
   * <pre>
   *&#47;Type of receipt. Ex: eSignature, paper, receipt_cart
   * </pre>
   */
  public java.lang.String getReceiptType() {
    java.lang.Object ref = receiptType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        receiptType_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string receipt_type = 14;</code>
   *
   * <pre>
   *&#47;Type of receipt. Ex: eSignature, paper, receipt_cart
   * </pre>
   */
  public com.google.protobuf.ByteString
      getReceiptTypeBytes() {
    java.lang.Object ref = receiptType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      receiptType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private void initFields() {
    txnType_ = com.eze.ezecli.TxnInput.TxnType.CARD_AUTH;
    amount_ = 0D;
    orderId_ = "";
    nonce_ = "";
    customerMobile_ = "";
    customerEmail_ = "";
    externalReference2_ = "";
    externalReference3_ = "";
    amountOther_ = 0D;
    chequeNumber_ = "";
    bankCode_ = "";
    chequeDate_ = "";
    additionalData_ = "";
    receiptType_ = "";
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasTxnType()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasAmount()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeEnum(1, txnType_.getNumber());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeDouble(2, amount_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeBytes(3, getOrderIdBytes());
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      output.writeBytes(4, getNonceBytes());
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      output.writeBytes(5, getCustomerMobileBytes());
    }
    if (((bitField0_ & 0x00000020) == 0x00000020)) {
      output.writeBytes(6, getCustomerEmailBytes());
    }
    if (((bitField0_ & 0x00000040) == 0x00000040)) {
      output.writeBytes(7, getExternalReference2Bytes());
    }
    if (((bitField0_ & 0x00000080) == 0x00000080)) {
      output.writeBytes(8, getExternalReference3Bytes());
    }
    if (((bitField0_ & 0x00000100) == 0x00000100)) {
      output.writeDouble(9, amountOther_);
    }
    if (((bitField0_ & 0x00000200) == 0x00000200)) {
      output.writeBytes(10, getChequeNumberBytes());
    }
    if (((bitField0_ & 0x00000400) == 0x00000400)) {
      output.writeBytes(11, getBankCodeBytes());
    }
    if (((bitField0_ & 0x00000800) == 0x00000800)) {
      output.writeBytes(12, getChequeDateBytes());
    }
    if (((bitField0_ & 0x00001000) == 0x00001000)) {
      output.writeBytes(13, getAdditionalDataBytes());
    }
    if (((bitField0_ & 0x00002000) == 0x00002000)) {
      output.writeBytes(14, getReceiptTypeBytes());
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, txnType_.getNumber());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, amount_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(3, getOrderIdBytes());
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(4, getNonceBytes());
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(5, getCustomerMobileBytes());
    }
    if (((bitField0_ & 0x00000020) == 0x00000020)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(6, getCustomerEmailBytes());
    }
    if (((bitField0_ & 0x00000040) == 0x00000040)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(7, getExternalReference2Bytes());
    }
    if (((bitField0_ & 0x00000080) == 0x00000080)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(8, getExternalReference3Bytes());
    }
    if (((bitField0_ & 0x00000100) == 0x00000100)) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(9, amountOther_);
    }
    if (((bitField0_ & 0x00000200) == 0x00000200)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(10, getChequeNumberBytes());
    }
    if (((bitField0_ & 0x00000400) == 0x00000400)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(11, getBankCodeBytes());
    }
    if (((bitField0_ & 0x00000800) == 0x00000800)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(12, getChequeDateBytes());
    }
    if (((bitField0_ & 0x00001000) == 0x00001000)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(13, getAdditionalDataBytes());
    }
    if (((bitField0_ & 0x00002000) == 0x00002000)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(14, getReceiptTypeBytes());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static com.eze.ezecli.TxnInput parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.eze.ezecli.TxnInput parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.eze.ezecli.TxnInput parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.eze.ezecli.TxnInput parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.eze.ezecli.TxnInput parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.eze.ezecli.TxnInput parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static com.eze.ezecli.TxnInput parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static com.eze.ezecli.TxnInput parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static com.eze.ezecli.TxnInput parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.eze.ezecli.TxnInput parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(com.eze.ezecli.TxnInput prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ezecli.TxnInput}
   *
   * <pre>
   **
   * TxnInput is a message representing the input to the transaction API. This API is used to initiate a transaction on the Ezetap Payment when you want to accept a payment.
   * </pre>
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ezecli.TxnInput)
      com.eze.ezecli.TxnInputOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.eze.ezecli.Ezetap.internal_static_ezecli_TxnInput_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.eze.ezecli.Ezetap.internal_static_ezecli_TxnInput_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.eze.ezecli.TxnInput.class, com.eze.ezecli.TxnInput.Builder.class);
    }

    // Construct using com.eze.ezecli.TxnInput.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      txnType_ = com.eze.ezecli.TxnInput.TxnType.CARD_AUTH;
      bitField0_ = (bitField0_ & ~0x00000001);
      amount_ = 0D;
      bitField0_ = (bitField0_ & ~0x00000002);
      orderId_ = "";
      bitField0_ = (bitField0_ & ~0x00000004);
      nonce_ = "";
      bitField0_ = (bitField0_ & ~0x00000008);
      customerMobile_ = "";
      bitField0_ = (bitField0_ & ~0x00000010);
      customerEmail_ = "";
      bitField0_ = (bitField0_ & ~0x00000020);
      externalReference2_ = "";
      bitField0_ = (bitField0_ & ~0x00000040);
      externalReference3_ = "";
      bitField0_ = (bitField0_ & ~0x00000080);
      amountOther_ = 0D;
      bitField0_ = (bitField0_ & ~0x00000100);
      chequeNumber_ = "";
      bitField0_ = (bitField0_ & ~0x00000200);
      bankCode_ = "";
      bitField0_ = (bitField0_ & ~0x00000400);
      chequeDate_ = "";
      bitField0_ = (bitField0_ & ~0x00000800);
      additionalData_ = "";
      bitField0_ = (bitField0_ & ~0x00001000);
      receiptType_ = "";
      bitField0_ = (bitField0_ & ~0x00002000);
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.eze.ezecli.Ezetap.internal_static_ezecli_TxnInput_descriptor;
    }

    public com.eze.ezecli.TxnInput getDefaultInstanceForType() {
      return com.eze.ezecli.TxnInput.getDefaultInstance();
    }

    public com.eze.ezecli.TxnInput build() {
      com.eze.ezecli.TxnInput result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.eze.ezecli.TxnInput buildPartial() {
      com.eze.ezecli.TxnInput result = new com.eze.ezecli.TxnInput(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.txnType_ = txnType_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.amount_ = amount_;
      if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
        to_bitField0_ |= 0x00000004;
      }
      result.orderId_ = orderId_;
      if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
        to_bitField0_ |= 0x00000008;
      }
      result.nonce_ = nonce_;
      if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
        to_bitField0_ |= 0x00000010;
      }
      result.customerMobile_ = customerMobile_;
      if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
        to_bitField0_ |= 0x00000020;
      }
      result.customerEmail_ = customerEmail_;
      if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
        to_bitField0_ |= 0x00000040;
      }
      result.externalReference2_ = externalReference2_;
      if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
        to_bitField0_ |= 0x00000080;
      }
      result.externalReference3_ = externalReference3_;
      if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
        to_bitField0_ |= 0x00000100;
      }
      result.amountOther_ = amountOther_;
      if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
        to_bitField0_ |= 0x00000200;
      }
      result.chequeNumber_ = chequeNumber_;
      if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
        to_bitField0_ |= 0x00000400;
      }
      result.bankCode_ = bankCode_;
      if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
        to_bitField0_ |= 0x00000800;
      }
      result.chequeDate_ = chequeDate_;
      if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
        to_bitField0_ |= 0x00001000;
      }
      result.additionalData_ = additionalData_;
      if (((from_bitField0_ & 0x00002000) == 0x00002000)) {
        to_bitField0_ |= 0x00002000;
      }
      result.receiptType_ = receiptType_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.eze.ezecli.TxnInput) {
        return mergeFrom((com.eze.ezecli.TxnInput)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.eze.ezecli.TxnInput other) {
      if (other == com.eze.ezecli.TxnInput.getDefaultInstance()) return this;
      if (other.hasTxnType()) {
        setTxnType(other.getTxnType());
      }
      if (other.hasAmount()) {
        setAmount(other.getAmount());
      }
      if (other.hasOrderId()) {
        bitField0_ |= 0x00000004;
        orderId_ = other.orderId_;
        onChanged();
      }
      if (other.hasNonce()) {
        bitField0_ |= 0x00000008;
        nonce_ = other.nonce_;
        onChanged();
      }
      if (other.hasCustomerMobile()) {
        bitField0_ |= 0x00000010;
        customerMobile_ = other.customerMobile_;
        onChanged();
      }
      if (other.hasCustomerEmail()) {
        bitField0_ |= 0x00000020;
        customerEmail_ = other.customerEmail_;
        onChanged();
      }
      if (other.hasExternalReference2()) {
        bitField0_ |= 0x00000040;
        externalReference2_ = other.externalReference2_;
        onChanged();
      }
      if (other.hasExternalReference3()) {
        bitField0_ |= 0x00000080;
        externalReference3_ = other.externalReference3_;
        onChanged();
      }
      if (other.hasAmountOther()) {
        setAmountOther(other.getAmountOther());
      }
      if (other.hasChequeNumber()) {
        bitField0_ |= 0x00000200;
        chequeNumber_ = other.chequeNumber_;
        onChanged();
      }
      if (other.hasBankCode()) {
        bitField0_ |= 0x00000400;
        bankCode_ = other.bankCode_;
        onChanged();
      }
      if (other.hasChequeDate()) {
        bitField0_ |= 0x00000800;
        chequeDate_ = other.chequeDate_;
        onChanged();
      }
      if (other.hasAdditionalData()) {
        bitField0_ |= 0x00001000;
        additionalData_ = other.additionalData_;
        onChanged();
      }
      if (other.hasReceiptType()) {
        bitField0_ |= 0x00002000;
        receiptType_ = other.receiptType_;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      if (!hasTxnType()) {
        
        return false;
      }
      if (!hasAmount()) {
        
        return false;
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.eze.ezecli.TxnInput parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.eze.ezecli.TxnInput) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.eze.ezecli.TxnInput.TxnType txnType_ = com.eze.ezecli.TxnInput.TxnType.CARD_AUTH;
    /**
     * <code>required .ezecli.TxnInput.TxnType txnType = 1;</code>
     *
     * <pre>
     *&#47;Type of the transaction
     * </pre>
     */
    public boolean hasTxnType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .ezecli.TxnInput.TxnType txnType = 1;</code>
     *
     * <pre>
     *&#47;Type of the transaction
     * </pre>
     */
    public com.eze.ezecli.TxnInput.TxnType getTxnType() {
      return txnType_;
    }
    /**
     * <code>required .ezecli.TxnInput.TxnType txnType = 1;</code>
     *
     * <pre>
     *&#47;Type of the transaction
     * </pre>
     */
    public Builder setTxnType(com.eze.ezecli.TxnInput.TxnType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      txnType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required .ezecli.TxnInput.TxnType txnType = 1;</code>
     *
     * <pre>
     *&#47;Type of the transaction
     * </pre>
     */
    public Builder clearTxnType() {
      bitField0_ = (bitField0_ & ~0x00000001);
      txnType_ = com.eze.ezecli.TxnInput.TxnType.CARD_AUTH;
      onChanged();
      return this;
    }

    private double amount_ ;
    /**
     * <code>required double amount = 2;</code>
     *
     * <pre>
     *&#47;Amount for the transaction
     * </pre>
     */
    public boolean hasAmount() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required double amount = 2;</code>
     *
     * <pre>
     *&#47;Amount for the transaction
     * </pre>
     */
    public double getAmount() {
      return amount_;
    }
    /**
     * <code>required double amount = 2;</code>
     *
     * <pre>
     *&#47;Amount for the transaction
     * </pre>
     */
    public Builder setAmount(double value) {
      bitField0_ |= 0x00000002;
      amount_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required double amount = 2;</code>
     *
     * <pre>
     *&#47;Amount for the transaction
     * </pre>
     */
    public Builder clearAmount() {
      bitField0_ = (bitField0_ & ~0x00000002);
      amount_ = 0D;
      onChanged();
      return this;
    }

    private java.lang.Object orderId_ = "";
    /**
     * <code>optional string orderId = 3;</code>
     *
     * <pre>
     *&#47;Order Id corresponding to the transaction
     * </pre>
     */
    public boolean hasOrderId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string orderId = 3;</code>
     *
     * <pre>
     *&#47;Order Id corresponding to the transaction
     * </pre>
     */
    public java.lang.String getOrderId() {
      java.lang.Object ref = orderId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          orderId_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string orderId = 3;</code>
     *
     * <pre>
     *&#47;Order Id corresponding to the transaction
     * </pre>
     */
    public com.google.protobuf.ByteString
        getOrderIdBytes() {
      java.lang.Object ref = orderId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        orderId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string orderId = 3;</code>
     *
     * <pre>
     *&#47;Order Id corresponding to the transaction
     * </pre>
     */
    public Builder setOrderId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      orderId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string orderId = 3;</code>
     *
     * <pre>
     *&#47;Order Id corresponding to the transaction
     * </pre>
     */
    public Builder clearOrderId() {
      bitField0_ = (bitField0_ & ~0x00000004);
      orderId_ = getDefaultInstance().getOrderId();
      onChanged();
      return this;
    }
    /**
     * <code>optional string orderId = 3;</code>
     *
     * <pre>
     *&#47;Order Id corresponding to the transaction
     * </pre>
     */
    public Builder setOrderIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      orderId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object nonce_ = "";
    /**
     * <code>optional string nonce = 4;</code>
     *
     * <pre>
     *&#47;Unique identifier for the transaction on the client app.
     * </pre>
     */
    public boolean hasNonce() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string nonce = 4;</code>
     *
     * <pre>
     *&#47;Unique identifier for the transaction on the client app.
     * </pre>
     */
    public java.lang.String getNonce() {
      java.lang.Object ref = nonce_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          nonce_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string nonce = 4;</code>
     *
     * <pre>
     *&#47;Unique identifier for the transaction on the client app.
     * </pre>
     */
    public com.google.protobuf.ByteString
        getNonceBytes() {
      java.lang.Object ref = nonce_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nonce_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string nonce = 4;</code>
     *
     * <pre>
     *&#47;Unique identifier for the transaction on the client app.
     * </pre>
     */
    public Builder setNonce(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      nonce_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string nonce = 4;</code>
     *
     * <pre>
     *&#47;Unique identifier for the transaction on the client app.
     * </pre>
     */
    public Builder clearNonce() {
      bitField0_ = (bitField0_ & ~0x00000008);
      nonce_ = getDefaultInstance().getNonce();
      onChanged();
      return this;
    }
    /**
     * <code>optional string nonce = 4;</code>
     *
     * <pre>
     *&#47;Unique identifier for the transaction on the client app.
     * </pre>
     */
    public Builder setNonceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      nonce_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object customerMobile_ = "";
    /**
     * <code>optional string customerMobile = 5;</code>
     *
     * <pre>
     *&#47;Mobile number of the transaction
     * </pre>
     */
    public boolean hasCustomerMobile() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string customerMobile = 5;</code>
     *
     * <pre>
     *&#47;Mobile number of the transaction
     * </pre>
     */
    public java.lang.String getCustomerMobile() {
      java.lang.Object ref = customerMobile_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          customerMobile_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string customerMobile = 5;</code>
     *
     * <pre>
     *&#47;Mobile number of the transaction
     * </pre>
     */
    public com.google.protobuf.ByteString
        getCustomerMobileBytes() {
      java.lang.Object ref = customerMobile_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        customerMobile_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string customerMobile = 5;</code>
     *
     * <pre>
     *&#47;Mobile number of the transaction
     * </pre>
     */
    public Builder setCustomerMobile(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
      customerMobile_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string customerMobile = 5;</code>
     *
     * <pre>
     *&#47;Mobile number of the transaction
     * </pre>
     */
    public Builder clearCustomerMobile() {
      bitField0_ = (bitField0_ & ~0x00000010);
      customerMobile_ = getDefaultInstance().getCustomerMobile();
      onChanged();
      return this;
    }
    /**
     * <code>optional string customerMobile = 5;</code>
     *
     * <pre>
     *&#47;Mobile number of the transaction
     * </pre>
     */
    public Builder setCustomerMobileBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
      customerMobile_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object customerEmail_ = "";
    /**
     * <code>optional string customerEmail = 6;</code>
     *
     * <pre>
     *&#47;Email address of the transaction
     * </pre>
     */
    public boolean hasCustomerEmail() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string customerEmail = 6;</code>
     *
     * <pre>
     *&#47;Email address of the transaction
     * </pre>
     */
    public java.lang.String getCustomerEmail() {
      java.lang.Object ref = customerEmail_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          customerEmail_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string customerEmail = 6;</code>
     *
     * <pre>
     *&#47;Email address of the transaction
     * </pre>
     */
    public com.google.protobuf.ByteString
        getCustomerEmailBytes() {
      java.lang.Object ref = customerEmail_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        customerEmail_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string customerEmail = 6;</code>
     *
     * <pre>
     *&#47;Email address of the transaction
     * </pre>
     */
    public Builder setCustomerEmail(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
      customerEmail_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string customerEmail = 6;</code>
     *
     * <pre>
     *&#47;Email address of the transaction
     * </pre>
     */
    public Builder clearCustomerEmail() {
      bitField0_ = (bitField0_ & ~0x00000020);
      customerEmail_ = getDefaultInstance().getCustomerEmail();
      onChanged();
      return this;
    }
    /**
     * <code>optional string customerEmail = 6;</code>
     *
     * <pre>
     *&#47;Email address of the transaction
     * </pre>
     */
    public Builder setCustomerEmailBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
      customerEmail_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object externalReference2_ = "";
    /**
     * <code>optional string externalReference2 = 7;</code>
     *
     * <pre>
     *&#47;External reference 2
     * </pre>
     */
    public boolean hasExternalReference2() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional string externalReference2 = 7;</code>
     *
     * <pre>
     *&#47;External reference 2
     * </pre>
     */
    public java.lang.String getExternalReference2() {
      java.lang.Object ref = externalReference2_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          externalReference2_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string externalReference2 = 7;</code>
     *
     * <pre>
     *&#47;External reference 2
     * </pre>
     */
    public com.google.protobuf.ByteString
        getExternalReference2Bytes() {
      java.lang.Object ref = externalReference2_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        externalReference2_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string externalReference2 = 7;</code>
     *
     * <pre>
     *&#47;External reference 2
     * </pre>
     */
    public Builder setExternalReference2(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
      externalReference2_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string externalReference2 = 7;</code>
     *
     * <pre>
     *&#47;External reference 2
     * </pre>
     */
    public Builder clearExternalReference2() {
      bitField0_ = (bitField0_ & ~0x00000040);
      externalReference2_ = getDefaultInstance().getExternalReference2();
      onChanged();
      return this;
    }
    /**
     * <code>optional string externalReference2 = 7;</code>
     *
     * <pre>
     *&#47;External reference 2
     * </pre>
     */
    public Builder setExternalReference2Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
      externalReference2_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object externalReference3_ = "";
    /**
     * <code>optional string externalReference3 = 8;</code>
     *
     * <pre>
     *&#47;External reference 3
     * </pre>
     */
    public boolean hasExternalReference3() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional string externalReference3 = 8;</code>
     *
     * <pre>
     *&#47;External reference 3
     * </pre>
     */
    public java.lang.String getExternalReference3() {
      java.lang.Object ref = externalReference3_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          externalReference3_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string externalReference3 = 8;</code>
     *
     * <pre>
     *&#47;External reference 3
     * </pre>
     */
    public com.google.protobuf.ByteString
        getExternalReference3Bytes() {
      java.lang.Object ref = externalReference3_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        externalReference3_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string externalReference3 = 8;</code>
     *
     * <pre>
     *&#47;External reference 3
     * </pre>
     */
    public Builder setExternalReference3(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
      externalReference3_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string externalReference3 = 8;</code>
     *
     * <pre>
     *&#47;External reference 3
     * </pre>
     */
    public Builder clearExternalReference3() {
      bitField0_ = (bitField0_ & ~0x00000080);
      externalReference3_ = getDefaultInstance().getExternalReference3();
      onChanged();
      return this;
    }
    /**
     * <code>optional string externalReference3 = 8;</code>
     *
     * <pre>
     *&#47;External reference 3
     * </pre>
     */
    public Builder setExternalReference3Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
      externalReference3_ = value;
      onChanged();
      return this;
    }

    private double amountOther_ ;
    /**
     * <code>optional double amountOther = 9;</code>
     *
     * <pre>
     *&#47;Other Amount; In case of cash back transactions. 
     * </pre>
     */
    public boolean hasAmountOther() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional double amountOther = 9;</code>
     *
     * <pre>
     *&#47;Other Amount; In case of cash back transactions. 
     * </pre>
     */
    public double getAmountOther() {
      return amountOther_;
    }
    /**
     * <code>optional double amountOther = 9;</code>
     *
     * <pre>
     *&#47;Other Amount; In case of cash back transactions. 
     * </pre>
     */
    public Builder setAmountOther(double value) {
      bitField0_ |= 0x00000100;
      amountOther_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional double amountOther = 9;</code>
     *
     * <pre>
     *&#47;Other Amount; In case of cash back transactions. 
     * </pre>
     */
    public Builder clearAmountOther() {
      bitField0_ = (bitField0_ & ~0x00000100);
      amountOther_ = 0D;
      onChanged();
      return this;
    }

    private java.lang.Object chequeNumber_ = "";
    /**
     * <code>optional string chequeNumber = 10;</code>
     *
     * <pre>
     *&#47;Cheque number if the transaction type is CHEQUE
     * </pre>
     */
    public boolean hasChequeNumber() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional string chequeNumber = 10;</code>
     *
     * <pre>
     *&#47;Cheque number if the transaction type is CHEQUE
     * </pre>
     */
    public java.lang.String getChequeNumber() {
      java.lang.Object ref = chequeNumber_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          chequeNumber_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string chequeNumber = 10;</code>
     *
     * <pre>
     *&#47;Cheque number if the transaction type is CHEQUE
     * </pre>
     */
    public com.google.protobuf.ByteString
        getChequeNumberBytes() {
      java.lang.Object ref = chequeNumber_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        chequeNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string chequeNumber = 10;</code>
     *
     * <pre>
     *&#47;Cheque number if the transaction type is CHEQUE
     * </pre>
     */
    public Builder setChequeNumber(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
      chequeNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string chequeNumber = 10;</code>
     *
     * <pre>
     *&#47;Cheque number if the transaction type is CHEQUE
     * </pre>
     */
    public Builder clearChequeNumber() {
      bitField0_ = (bitField0_ & ~0x00000200);
      chequeNumber_ = getDefaultInstance().getChequeNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional string chequeNumber = 10;</code>
     *
     * <pre>
     *&#47;Cheque number if the transaction type is CHEQUE
     * </pre>
     */
    public Builder setChequeNumberBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
      chequeNumber_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object bankCode_ = "";
    /**
     * <code>optional string bankCode = 11;</code>
     *
     * <pre>
     *&#47;MICR code of the bank for CHEQUE payments
     * </pre>
     */
    public boolean hasBankCode() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>optional string bankCode = 11;</code>
     *
     * <pre>
     *&#47;MICR code of the bank for CHEQUE payments
     * </pre>
     */
    public java.lang.String getBankCode() {
      java.lang.Object ref = bankCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          bankCode_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string bankCode = 11;</code>
     *
     * <pre>
     *&#47;MICR code of the bank for CHEQUE payments
     * </pre>
     */
    public com.google.protobuf.ByteString
        getBankCodeBytes() {
      java.lang.Object ref = bankCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bankCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string bankCode = 11;</code>
     *
     * <pre>
     *&#47;MICR code of the bank for CHEQUE payments
     * </pre>
     */
    public Builder setBankCode(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
      bankCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string bankCode = 11;</code>
     *
     * <pre>
     *&#47;MICR code of the bank for CHEQUE payments
     * </pre>
     */
    public Builder clearBankCode() {
      bitField0_ = (bitField0_ & ~0x00000400);
      bankCode_ = getDefaultInstance().getBankCode();
      onChanged();
      return this;
    }
    /**
     * <code>optional string bankCode = 11;</code>
     *
     * <pre>
     *&#47;MICR code of the bank for CHEQUE payments
     * </pre>
     */
    public Builder setBankCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
      bankCode_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object chequeDate_ = "";
    /**
     * <code>optional string chequeDate = 12;</code>
     *
     * <pre>
     *&#47;Date on the cheque for CHEQUE payments
     * </pre>
     */
    public boolean hasChequeDate() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    /**
     * <code>optional string chequeDate = 12;</code>
     *
     * <pre>
     *&#47;Date on the cheque for CHEQUE payments
     * </pre>
     */
    public java.lang.String getChequeDate() {
      java.lang.Object ref = chequeDate_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          chequeDate_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string chequeDate = 12;</code>
     *
     * <pre>
     *&#47;Date on the cheque for CHEQUE payments
     * </pre>
     */
    public com.google.protobuf.ByteString
        getChequeDateBytes() {
      java.lang.Object ref = chequeDate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        chequeDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string chequeDate = 12;</code>
     *
     * <pre>
     *&#47;Date on the cheque for CHEQUE payments
     * </pre>
     */
    public Builder setChequeDate(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000800;
      chequeDate_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string chequeDate = 12;</code>
     *
     * <pre>
     *&#47;Date on the cheque for CHEQUE payments
     * </pre>
     */
    public Builder clearChequeDate() {
      bitField0_ = (bitField0_ & ~0x00000800);
      chequeDate_ = getDefaultInstance().getChequeDate();
      onChanged();
      return this;
    }
    /**
     * <code>optional string chequeDate = 12;</code>
     *
     * <pre>
     *&#47;Date on the cheque for CHEQUE payments
     * </pre>
     */
    public Builder setChequeDateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000800;
      chequeDate_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object additionalData_ = "";
    /**
     * <code>optional string additionalData = 13;</code>
     *
     * <pre>
     *&#47;Any additional JSON data to be appended to the transaction input 
     * </pre>
     */
    public boolean hasAdditionalData() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    /**
     * <code>optional string additionalData = 13;</code>
     *
     * <pre>
     *&#47;Any additional JSON data to be appended to the transaction input 
     * </pre>
     */
    public java.lang.String getAdditionalData() {
      java.lang.Object ref = additionalData_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          additionalData_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string additionalData = 13;</code>
     *
     * <pre>
     *&#47;Any additional JSON data to be appended to the transaction input 
     * </pre>
     */
    public com.google.protobuf.ByteString
        getAdditionalDataBytes() {
      java.lang.Object ref = additionalData_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        additionalData_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string additionalData = 13;</code>
     *
     * <pre>
     *&#47;Any additional JSON data to be appended to the transaction input 
     * </pre>
     */
    public Builder setAdditionalData(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00001000;
      additionalData_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string additionalData = 13;</code>
     *
     * <pre>
     *&#47;Any additional JSON data to be appended to the transaction input 
     * </pre>
     */
    public Builder clearAdditionalData() {
      bitField0_ = (bitField0_ & ~0x00001000);
      additionalData_ = getDefaultInstance().getAdditionalData();
      onChanged();
      return this;
    }
    /**
     * <code>optional string additionalData = 13;</code>
     *
     * <pre>
     *&#47;Any additional JSON data to be appended to the transaction input 
     * </pre>
     */
    public Builder setAdditionalDataBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00001000;
      additionalData_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object receiptType_ = "";
    /**
     * <code>optional string receipt_type = 14;</code>
     *
     * <pre>
     *&#47;Type of receipt. Ex: eSignature, paper, receipt_cart
     * </pre>
     */
    public boolean hasReceiptType() {
      return ((bitField0_ & 0x00002000) == 0x00002000);
    }
    /**
     * <code>optional string receipt_type = 14;</code>
     *
     * <pre>
     *&#47;Type of receipt. Ex: eSignature, paper, receipt_cart
     * </pre>
     */
    public java.lang.String getReceiptType() {
      java.lang.Object ref = receiptType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          receiptType_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string receipt_type = 14;</code>
     *
     * <pre>
     *&#47;Type of receipt. Ex: eSignature, paper, receipt_cart
     * </pre>
     */
    public com.google.protobuf.ByteString
        getReceiptTypeBytes() {
      java.lang.Object ref = receiptType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        receiptType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string receipt_type = 14;</code>
     *
     * <pre>
     *&#47;Type of receipt. Ex: eSignature, paper, receipt_cart
     * </pre>
     */
    public Builder setReceiptType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00002000;
      receiptType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string receipt_type = 14;</code>
     *
     * <pre>
     *&#47;Type of receipt. Ex: eSignature, paper, receipt_cart
     * </pre>
     */
    public Builder clearReceiptType() {
      bitField0_ = (bitField0_ & ~0x00002000);
      receiptType_ = getDefaultInstance().getReceiptType();
      onChanged();
      return this;
    }
    /**
     * <code>optional string receipt_type = 14;</code>
     *
     * <pre>
     *&#47;Type of receipt. Ex: eSignature, paper, receipt_cart
     * </pre>
     */
    public Builder setReceiptTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00002000;
      receiptType_ = value;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:ezecli.TxnInput)
  }

  static {
    defaultInstance = new TxnInput(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:ezecli.TxnInput)
}

