// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ezetap.proto

package com.eze.ezecli;

public interface TxnInputOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ezecli.TxnInput)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required .ezecli.TxnInput.TxnType txnType = 1;</code>
   *
   * <pre>
   *&#47;Type of the transaction
   * </pre>
   */
  boolean hasTxnType();
  /**
   * <code>required .ezecli.TxnInput.TxnType txnType = 1;</code>
   *
   * <pre>
   *&#47;Type of the transaction
   * </pre>
   */
  com.eze.ezecli.TxnInput.TxnType getTxnType();

  /**
   * <code>required double amount = 2;</code>
   *
   * <pre>
   *&#47;Amount for the transaction
   * </pre>
   */
  boolean hasAmount();
  /**
   * <code>required double amount = 2;</code>
   *
   * <pre>
   *&#47;Amount for the transaction
   * </pre>
   */
  double getAmount();

  /**
   * <code>optional string orderId = 3;</code>
   *
   * <pre>
   *&#47;Order Id corresponding to the transaction
   * </pre>
   */
  boolean hasOrderId();
  /**
   * <code>optional string orderId = 3;</code>
   *
   * <pre>
   *&#47;Order Id corresponding to the transaction
   * </pre>
   */
  java.lang.String getOrderId();
  /**
   * <code>optional string orderId = 3;</code>
   *
   * <pre>
   *&#47;Order Id corresponding to the transaction
   * </pre>
   */
  com.google.protobuf.ByteString
      getOrderIdBytes();

  /**
   * <code>optional string nonce = 4;</code>
   *
   * <pre>
   *&#47;Unique identifier for the transaction on the client app.
   * </pre>
   */
  boolean hasNonce();
  /**
   * <code>optional string nonce = 4;</code>
   *
   * <pre>
   *&#47;Unique identifier for the transaction on the client app.
   * </pre>
   */
  java.lang.String getNonce();
  /**
   * <code>optional string nonce = 4;</code>
   *
   * <pre>
   *&#47;Unique identifier for the transaction on the client app.
   * </pre>
   */
  com.google.protobuf.ByteString
      getNonceBytes();

  /**
   * <code>optional string customerMobile = 5;</code>
   *
   * <pre>
   *&#47;Mobile number of the transaction
   * </pre>
   */
  boolean hasCustomerMobile();
  /**
   * <code>optional string customerMobile = 5;</code>
   *
   * <pre>
   *&#47;Mobile number of the transaction
   * </pre>
   */
  java.lang.String getCustomerMobile();
  /**
   * <code>optional string customerMobile = 5;</code>
   *
   * <pre>
   *&#47;Mobile number of the transaction
   * </pre>
   */
  com.google.protobuf.ByteString
      getCustomerMobileBytes();

  /**
   * <code>optional string customerEmail = 6;</code>
   *
   * <pre>
   *&#47;Email address of the transaction
   * </pre>
   */
  boolean hasCustomerEmail();
  /**
   * <code>optional string customerEmail = 6;</code>
   *
   * <pre>
   *&#47;Email address of the transaction
   * </pre>
   */
  java.lang.String getCustomerEmail();
  /**
   * <code>optional string customerEmail = 6;</code>
   *
   * <pre>
   *&#47;Email address of the transaction
   * </pre>
   */
  com.google.protobuf.ByteString
      getCustomerEmailBytes();

  /**
   * <code>optional string externalReference2 = 7;</code>
   *
   * <pre>
   *&#47;External reference 2
   * </pre>
   */
  boolean hasExternalReference2();
  /**
   * <code>optional string externalReference2 = 7;</code>
   *
   * <pre>
   *&#47;External reference 2
   * </pre>
   */
  java.lang.String getExternalReference2();
  /**
   * <code>optional string externalReference2 = 7;</code>
   *
   * <pre>
   *&#47;External reference 2
   * </pre>
   */
  com.google.protobuf.ByteString
      getExternalReference2Bytes();

  /**
   * <code>optional string externalReference3 = 8;</code>
   *
   * <pre>
   *&#47;External reference 3
   * </pre>
   */
  boolean hasExternalReference3();
  /**
   * <code>optional string externalReference3 = 8;</code>
   *
   * <pre>
   *&#47;External reference 3
   * </pre>
   */
  java.lang.String getExternalReference3();
  /**
   * <code>optional string externalReference3 = 8;</code>
   *
   * <pre>
   *&#47;External reference 3
   * </pre>
   */
  com.google.protobuf.ByteString
      getExternalReference3Bytes();

  /**
   * <code>optional double amountOther = 9;</code>
   *
   * <pre>
   *&#47;Other Amount; In case of cash back transactions. 
   * </pre>
   */
  boolean hasAmountOther();
  /**
   * <code>optional double amountOther = 9;</code>
   *
   * <pre>
   *&#47;Other Amount; In case of cash back transactions. 
   * </pre>
   */
  double getAmountOther();

  /**
   * <code>optional string chequeNumber = 10;</code>
   *
   * <pre>
   *&#47;Cheque number if the transaction type is CHEQUE
   * </pre>
   */
  boolean hasChequeNumber();
  /**
   * <code>optional string chequeNumber = 10;</code>
   *
   * <pre>
   *&#47;Cheque number if the transaction type is CHEQUE
   * </pre>
   */
  java.lang.String getChequeNumber();
  /**
   * <code>optional string chequeNumber = 10;</code>
   *
   * <pre>
   *&#47;Cheque number if the transaction type is CHEQUE
   * </pre>
   */
  com.google.protobuf.ByteString
      getChequeNumberBytes();

  /**
   * <code>optional string bankCode = 11;</code>
   *
   * <pre>
   *&#47;MICR code of the bank for CHEQUE payments
   * </pre>
   */
  boolean hasBankCode();
  /**
   * <code>optional string bankCode = 11;</code>
   *
   * <pre>
   *&#47;MICR code of the bank for CHEQUE payments
   * </pre>
   */
  java.lang.String getBankCode();
  /**
   * <code>optional string bankCode = 11;</code>
   *
   * <pre>
   *&#47;MICR code of the bank for CHEQUE payments
   * </pre>
   */
  com.google.protobuf.ByteString
      getBankCodeBytes();

  /**
   * <code>optional string chequeDate = 12;</code>
   *
   * <pre>
   *&#47;Date on the cheque for CHEQUE payments
   * </pre>
   */
  boolean hasChequeDate();
  /**
   * <code>optional string chequeDate = 12;</code>
   *
   * <pre>
   *&#47;Date on the cheque for CHEQUE payments
   * </pre>
   */
  java.lang.String getChequeDate();
  /**
   * <code>optional string chequeDate = 12;</code>
   *
   * <pre>
   *&#47;Date on the cheque for CHEQUE payments
   * </pre>
   */
  com.google.protobuf.ByteString
      getChequeDateBytes();

  /**
   * <code>optional string additionalData = 13;</code>
   *
   * <pre>
   *&#47;Any additional JSON data to be appended to the transaction input 
   * </pre>
   */
  boolean hasAdditionalData();
  /**
   * <code>optional string additionalData = 13;</code>
   *
   * <pre>
   *&#47;Any additional JSON data to be appended to the transaction input 
   * </pre>
   */
  java.lang.String getAdditionalData();
  /**
   * <code>optional string additionalData = 13;</code>
   *
   * <pre>
   *&#47;Any additional JSON data to be appended to the transaction input 
   * </pre>
   */
  com.google.protobuf.ByteString
      getAdditionalDataBytes();

  /**
   * <code>optional string receipt_type = 14;</code>
   *
   * <pre>
   *&#47;Type of receipt. Ex: eSignature, paper, receipt_cart
   * </pre>
   */
  boolean hasReceiptType();
  /**
   * <code>optional string receipt_type = 14;</code>
   *
   * <pre>
   *&#47;Type of receipt. Ex: eSignature, paper, receipt_cart
   * </pre>
   */
  java.lang.String getReceiptType();
  /**
   * <code>optional string receipt_type = 14;</code>
   *
   * <pre>
   *&#47;Type of receipt. Ex: eSignature, paper, receipt_cart
   * </pre>
   */
  com.google.protobuf.ByteString
      getReceiptTypeBytes();
}
