// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ezetap.proto

package com.eze.ezecli;

public interface TxnOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ezecli.Txn)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required .ezecli.Txn.TxnType txnType = 1;</code>
   *
   * <pre>
   *&#47;Type of the transaction
   * </pre>
   */
  boolean hasTxnType();
  /**
   * <code>required .ezecli.Txn.TxnType txnType = 1;</code>
   *
   * <pre>
   *&#47;Type of the transaction
   * </pre>
   */
  com.eze.ezecli.Txn.TxnType getTxnType();

  /**
   * <code>required double amount = 2;</code>
   *
   * <pre>
   *&#47;Amount for the transaction
   * </pre>
   */
  boolean hasAmount();
  /**
   * <code>required double amount = 2;</code>
   *
   * <pre>
   *&#47;Amount for the transaction
   * </pre>
   */
  double getAmount();

  /**
   * <code>required string transactionId = 3;</code>
   *
   * <pre>
   *&#47;ID of the transaction
   * </pre>
   */
  boolean hasTransactionId();
  /**
   * <code>required string transactionId = 3;</code>
   *
   * <pre>
   *&#47;ID of the transaction
   * </pre>
   */
  java.lang.String getTransactionId();
  /**
   * <code>required string transactionId = 3;</code>
   *
   * <pre>
   *&#47;ID of the transaction
   * </pre>
   */
  com.google.protobuf.ByteString
      getTransactionIdBytes();

  /**
   * <code>required string timestamp = 4;</code>
   *
   * <pre>
   *&#47;Datetime of the transaction                                                 
   * </pre>
   */
  boolean hasTimestamp();
  /**
   * <code>required string timestamp = 4;</code>
   *
   * <pre>
   *&#47;Datetime of the transaction                                                 
   * </pre>
   */
  java.lang.String getTimestamp();
  /**
   * <code>required string timestamp = 4;</code>
   *
   * <pre>
   *&#47;Datetime of the transaction                                                 
   * </pre>
   */
  com.google.protobuf.ByteString
      getTimestampBytes();

  /**
   * <code>required string receiptUrl = 5;</code>
   *
   * <pre>
   *&#47;Short URL of the transaction to retrieve receipt                                                         
   * </pre>
   */
  boolean hasReceiptUrl();
  /**
   * <code>required string receiptUrl = 5;</code>
   *
   * <pre>
   *&#47;Short URL of the transaction to retrieve receipt                                                         
   * </pre>
   */
  java.lang.String getReceiptUrl();
  /**
   * <code>required string receiptUrl = 5;</code>
   *
   * <pre>
   *&#47;Short URL of the transaction to retrieve receipt                                                         
   * </pre>
   */
  com.google.protobuf.ByteString
      getReceiptUrlBytes();

  /**
   * <code>required string orderId = 6;</code>
   *
   * <pre>
   *&#47;Order ID of the transaction
   * </pre>
   */
  boolean hasOrderId();
  /**
   * <code>required string orderId = 6;</code>
   *
   * <pre>
   *&#47;Order ID of the transaction
   * </pre>
   */
  java.lang.String getOrderId();
  /**
   * <code>required string orderId = 6;</code>
   *
   * <pre>
   *&#47;Order ID of the transaction
   * </pre>
   */
  com.google.protobuf.ByteString
      getOrderIdBytes();

  /**
   * <code>required string externalReferenceNumber2 = 7;</code>
   *
   * <pre>
   *&#47;External reference 2
   * </pre>
   */
  boolean hasExternalReferenceNumber2();
  /**
   * <code>required string externalReferenceNumber2 = 7;</code>
   *
   * <pre>
   *&#47;External reference 2
   * </pre>
   */
  java.lang.String getExternalReferenceNumber2();
  /**
   * <code>required string externalReferenceNumber2 = 7;</code>
   *
   * <pre>
   *&#47;External reference 2
   * </pre>
   */
  com.google.protobuf.ByteString
      getExternalReferenceNumber2Bytes();

  /**
   * <code>required string externalReferenceNumber3 = 8;</code>
   *
   * <pre>
   *&#47;External reference 3
   * </pre>
   */
  boolean hasExternalReferenceNumber3();
  /**
   * <code>required string externalReferenceNumber3 = 8;</code>
   *
   * <pre>
   *&#47;External reference 3
   * </pre>
   */
  java.lang.String getExternalReferenceNumber3();
  /**
   * <code>required string externalReferenceNumber3 = 8;</code>
   *
   * <pre>
   *&#47;External reference 3
   * </pre>
   */
  com.google.protobuf.ByteString
      getExternalReferenceNumber3Bytes();

  /**
   * <code>required string customerMobileNumber = 9;</code>
   *
   * <pre>
   *&#47;Mobile number of the customer 
   * </pre>
   */
  boolean hasCustomerMobileNumber();
  /**
   * <code>required string customerMobileNumber = 9;</code>
   *
   * <pre>
   *&#47;Mobile number of the customer 
   * </pre>
   */
  java.lang.String getCustomerMobileNumber();
  /**
   * <code>required string customerMobileNumber = 9;</code>
   *
   * <pre>
   *&#47;Mobile number of the customer 
   * </pre>
   */
  com.google.protobuf.ByteString
      getCustomerMobileNumberBytes();

  /**
   * <code>required string customerName = 10;</code>
   *
   * <pre>
   *&#47;Name of the customer            
   * </pre>
   */
  boolean hasCustomerName();
  /**
   * <code>required string customerName = 10;</code>
   *
   * <pre>
   *&#47;Name of the customer            
   * </pre>
   */
  java.lang.String getCustomerName();
  /**
   * <code>required string customerName = 10;</code>
   *
   * <pre>
   *&#47;Name of the customer            
   * </pre>
   */
  com.google.protobuf.ByteString
      getCustomerNameBytes();

  /**
   * <code>required string status = 11;</code>
   *
   * <pre>
   *&#47;Status of the transaction  
   * </pre>
   */
  boolean hasStatus();
  /**
   * <code>required string status = 11;</code>
   *
   * <pre>
   *&#47;Status of the transaction  
   * </pre>
   */
  java.lang.String getStatus();
  /**
   * <code>required string status = 11;</code>
   *
   * <pre>
   *&#47;Status of the transaction  
   * </pre>
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>optional string userAgreement = 12;</code>
   *
   * <pre>
   *&#47;Bank's user agreement 
   * </pre>
   */
  boolean hasUserAgreement();
  /**
   * <code>optional string userAgreement = 12;</code>
   *
   * <pre>
   *&#47;Bank's user agreement 
   * </pre>
   */
  java.lang.String getUserAgreement();
  /**
   * <code>optional string userAgreement = 12;</code>
   *
   * <pre>
   *&#47;Bank's user agreement 
   * </pre>
   */
  com.google.protobuf.ByteString
      getUserAgreementBytes();

  /**
   * <code>optional string authCode = 13;</code>
   *
   * <pre>
   *&#47;Auth code of the transaction
   * </pre>
   */
  boolean hasAuthCode();
  /**
   * <code>optional string authCode = 13;</code>
   *
   * <pre>
   *&#47;Auth code of the transaction
   * </pre>
   */
  java.lang.String getAuthCode();
  /**
   * <code>optional string authCode = 13;</code>
   *
   * <pre>
   *&#47;Auth code of the transaction
   * </pre>
   */
  com.google.protobuf.ByteString
      getAuthCodeBytes();

  /**
   * <code>optional string lastFoundDigits = 14;</code>
   *
   * <pre>
   *&#47;Last four digits of the card
   * </pre>
   */
  boolean hasLastFoundDigits();
  /**
   * <code>optional string lastFoundDigits = 14;</code>
   *
   * <pre>
   *&#47;Last four digits of the card
   * </pre>
   */
  java.lang.String getLastFoundDigits();
  /**
   * <code>optional string lastFoundDigits = 14;</code>
   *
   * <pre>
   *&#47;Last four digits of the card
   * </pre>
   */
  com.google.protobuf.ByteString
      getLastFoundDigitsBytes();

  /**
   * <code>optional string cardBrand = 15;</code>
   *
   * <pre>
   *&#47;Brand of the card i.e., VISA, RUPAY etc
   * </pre>
   */
  boolean hasCardBrand();
  /**
   * <code>optional string cardBrand = 15;</code>
   *
   * <pre>
   *&#47;Brand of the card i.e., VISA, RUPAY etc
   * </pre>
   */
  java.lang.String getCardBrand();
  /**
   * <code>optional string cardBrand = 15;</code>
   *
   * <pre>
   *&#47;Brand of the card i.e., VISA, RUPAY etc
   * </pre>
   */
  com.google.protobuf.ByteString
      getCardBrandBytes();

  /**
   * <code>optional string invoiceNumber = 16;</code>
   *
   * <pre>
   *&#47;Invoice number of the transaction
   * </pre>
   */
  boolean hasInvoiceNumber();
  /**
   * <code>optional string invoiceNumber = 16;</code>
   *
   * <pre>
   *&#47;Invoice number of the transaction
   * </pre>
   */
  java.lang.String getInvoiceNumber();
  /**
   * <code>optional string invoiceNumber = 16;</code>
   *
   * <pre>
   *&#47;Invoice number of the transaction
   * </pre>
   */
  com.google.protobuf.ByteString
      getInvoiceNumberBytes();

  /**
   * <code>optional string batchNumber = 17;</code>
   *
   * <pre>
   *&#47;Batch number of the transaction
   * </pre>
   */
  boolean hasBatchNumber();
  /**
   * <code>optional string batchNumber = 17;</code>
   *
   * <pre>
   *&#47;Batch number of the transaction
   * </pre>
   */
  java.lang.String getBatchNumber();
  /**
   * <code>optional string batchNumber = 17;</code>
   *
   * <pre>
   *&#47;Batch number of the transaction
   * </pre>
   */
  com.google.protobuf.ByteString
      getBatchNumberBytes();

  /**
   * <code>optional string mid = 18;</code>
   *
   * <pre>
   *&#47;MID of the transaction
   * </pre>
   */
  boolean hasMid();
  /**
   * <code>optional string mid = 18;</code>
   *
   * <pre>
   *&#47;MID of the transaction
   * </pre>
   */
  java.lang.String getMid();
  /**
   * <code>optional string mid = 18;</code>
   *
   * <pre>
   *&#47;MID of the transaction
   * </pre>
   */
  com.google.protobuf.ByteString
      getMidBytes();

  /**
   * <code>optional string tid = 19;</code>
   *
   * <pre>
   *&#47;TID of the terminal on which the transaction happened
   * </pre>
   */
  boolean hasTid();
  /**
   * <code>optional string tid = 19;</code>
   *
   * <pre>
   *&#47;TID of the terminal on which the transaction happened
   * </pre>
   */
  java.lang.String getTid();
  /**
   * <code>optional string tid = 19;</code>
   *
   * <pre>
   *&#47;TID of the terminal on which the transaction happened
   * </pre>
   */
  com.google.protobuf.ByteString
      getTidBytes();

  /**
   * <code>optional string reverseRefNumber = 20;</code>
   *
   * <pre>
   *&#47;Reverse ref num of the transaction
   * </pre>
   */
  boolean hasReverseRefNumber();
  /**
   * <code>optional string reverseRefNumber = 20;</code>
   *
   * <pre>
   *&#47;Reverse ref num of the transaction
   * </pre>
   */
  java.lang.String getReverseRefNumber();
  /**
   * <code>optional string reverseRefNumber = 20;</code>
   *
   * <pre>
   *&#47;Reverse ref num of the transaction
   * </pre>
   */
  com.google.protobuf.ByteString
      getReverseRefNumberBytes();

  /**
   * <code>optional string chequeNumber = 21;</code>
   *
   * <pre>
   *&#47;Cheque number 
   * </pre>
   */
  boolean hasChequeNumber();
  /**
   * <code>optional string chequeNumber = 21;</code>
   *
   * <pre>
   *&#47;Cheque number 
   * </pre>
   */
  java.lang.String getChequeNumber();
  /**
   * <code>optional string chequeNumber = 21;</code>
   *
   * <pre>
   *&#47;Cheque number 
   * </pre>
   */
  com.google.protobuf.ByteString
      getChequeNumberBytes();

  /**
   * <code>optional string bankCode = 22;</code>
   *
   * <pre>
   *&#47;MICR code of the bank
   * </pre>
   */
  boolean hasBankCode();
  /**
   * <code>optional string bankCode = 22;</code>
   *
   * <pre>
   *&#47;MICR code of the bank
   * </pre>
   */
  java.lang.String getBankCode();
  /**
   * <code>optional string bankCode = 22;</code>
   *
   * <pre>
   *&#47;MICR code of the bank
   * </pre>
   */
  com.google.protobuf.ByteString
      getBankCodeBytes();

  /**
   * <code>optional string chequeDate = 23;</code>
   *
   * <pre>
   *&#47;Date on the cheque
   * </pre>
   */
  boolean hasChequeDate();
  /**
   * <code>optional string chequeDate = 23;</code>
   *
   * <pre>
   *&#47;Date on the cheque
   * </pre>
   */
  java.lang.String getChequeDate();
  /**
   * <code>optional string chequeDate = 23;</code>
   *
   * <pre>
   *&#47;Date on the cheque
   * </pre>
   */
  com.google.protobuf.ByteString
      getChequeDateBytes();

  /**
   * <code>optional string settlementStatus = 24;</code>
   *
   * <pre>
   *&#47;Settlement status of the transaction
   * </pre>
   */
  boolean hasSettlementStatus();
  /**
   * <code>optional string settlementStatus = 24;</code>
   *
   * <pre>
   *&#47;Settlement status of the transaction
   * </pre>
   */
  java.lang.String getSettlementStatus();
  /**
   * <code>optional string settlementStatus = 24;</code>
   *
   * <pre>
   *&#47;Settlement status of the transaction
   * </pre>
   */
  com.google.protobuf.ByteString
      getSettlementStatusBytes();

  /**
   * <code>optional bool voidable = 25;</code>
   *
   * <pre>
   *&#47;Boolean denotes if the transaction is voidable
   * </pre>
   */
  boolean hasVoidable();
  /**
   * <code>optional bool voidable = 25;</code>
   *
   * <pre>
   *&#47;Boolean denotes if the transaction is voidable
   * </pre>
   */
  boolean getVoidable();

  /**
   * <code>optional string serverResponse = 26;</code>
   *
   * <pre>
   *&#47;Server response- as is. Please refer server api-docs. 
   * </pre>
   */
  boolean hasServerResponse();
  /**
   * <code>optional string serverResponse = 26;</code>
   *
   * <pre>
   *&#47;Server response- as is. Please refer server api-docs. 
   * </pre>
   */
  java.lang.String getServerResponse();
  /**
   * <code>optional string serverResponse = 26;</code>
   *
   * <pre>
   *&#47;Server response- as is. Please refer server api-docs. 
   * </pre>
   */
  com.google.protobuf.ByteString
      getServerResponseBytes();
}
