// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ezetap.proto

package com.eze.ezecli;

public interface TxnStatusInputOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ezecli.TxnStatusInput)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required string nonce = 1;</code>
   *
   * <pre>
   *&#47;nonce of the transaction. This is a unique identifier generated by the calling app to identify the transaction initiated and is used to check on the transaction.
   * </pre>
   */
  boolean hasNonce();
  /**
   * <code>required string nonce = 1;</code>
   *
   * <pre>
   *&#47;nonce of the transaction. This is a unique identifier generated by the calling app to identify the transaction initiated and is used to check on the transaction.
   * </pre>
   */
  java.lang.String getNonce();
  /**
   * <code>required string nonce = 1;</code>
   *
   * <pre>
   *&#47;nonce of the transaction. This is a unique identifier generated by the calling app to identify the transaction initiated and is used to check on the transaction.
   * </pre>
   */
  com.google.protobuf.ByteString
      getNonceBytes();
}
